name: vitamui-mongo-dev
services:
  mongo-dev:
    image: mongodb/mongodb-community-server:8.0.23-ubuntu2204
    container_name: vitamui-mongo
    hostname: vitamui-mongo

    ports:
      # 27018 is selected in order to avoid a conflict with Vitam docker instance
      - "27018:27018"
    volumes:
      # if you wish to setup additional user accounts specific per DB or with different roles you can use following entry point
      - "$PWD/mongo-entrypoint:/scripts/mongo/data"
      - "$PWD/replica-set/:/scripts/mongo/replica-set"
    networks:
      - local_vitamui_network

    # no --auth is needed here as presence of username and password add this option automatically
    command: mongod --replSet "rs0" --port=27018

  mongonaut-dev:
    container_name: vitamui-mongonaut
    image: ghcr.io/withzu/mongonaut:latest
    restart: unless-stopped
    ports:
      - "18081:8081"
    depends_on:
      - mongo-dev
    networks:
      - local_vitamui_network
    environment:
      MONGO_CONNECTION_URL: "mongodb://mongod_dbuser_admin:mongod_dbpwd_admin@mongo-dev:27018/"
      MONGONAUT_AUTH_MODE: "NONE"

  dbgate-dev:
    container_name: vitamui-dbgate
    image: dbgate/dbgate:latest
    restart: unless-stopped
    ports:
      - "18082:3000"
    depends_on:
      - mongo-dev
    networks:
      - local_vitamui_network
    environment:
      CONNECTIONS: vitamui
      LABEL_vitamui: vitamui
      URL_vitamui: "mongodb://mongod_dbuser_admin:mongod_dbpwd_admin@mongo-dev:27018/?directConnection=true"
      ENGINE_vitamui: "mongo@dbgate-plugin-mongo"

networks:
  local_vitamui_network:
    name: mongo_default
