---
- block:

  - name: Install Apache package for displaying data content
    package:
      name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      state: latest
    register: result
    retries: "{{ packages_install_retries_number | default(2) }}"
    until: result is succeeded
    delay: "{{ packages_install_retries_delay | default(10) }}"

  - name: add vitamui group to apache user
    user:
      name: "{{ 'www-data' if ansible_os_family == 'Debian' else 'httpd' }}"
      groups: vitamui

  - name: copy theme files
    copy:
      src: .theme
      dest: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}"
      owner: root
      mode: 0644

  - name: add Apache configuration file for browser
    template:
      src: "{{ item }}.j2"
      dest: "{{ '/etc/apache2/sites-available' if ansible_os_family == 'Debian' else '/etc/httpd/conf.d' }}/{{ item }}"
      mode: 0500
      owner: root
    notify: restart apache
    with_items:
      - httpd-offer-view.conf

  - name: activate offer view in Debian only
    file:
      src: '/etc/apache2/sites-available/{{ item }}'
      dest: '/etc/apache2/sites-enabled/{{ item }}'
      state: link
    when: ansible_os_family == "Debian"
    notify: restart apache
    with_items:
      - httpd-offer-view.conf

  - meta: flush_handlers

  - name: Ensure Apache autostart && Apache is started
    service:
      name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
      enabled: yes
      state: started

  when: extra | d(false)
