package fr.gouv.vitamui.commons.api.enums;

public enum ErrorImportFileMessage {

    FILE_IS_EMPTY,
    FILE_SIZE_TOO_BIG,
    ONLY_ONE_HEADER_INCORRECT_SEPARATOR,
    FILE_MUST_RESPECT_COLUMNS_LENGTH,
    FILE_MUST_RESPECT_COLUMN_NAME,
    AT_LEAST_ONE_LINE,
    BAD_ROWS_LENGTH_IN_LINE,
    MANDATORY_VALUE,
    NOT_ALLOWED_VALUE,
    ISO_8859_1_ONLY,
    REJECT_BY_VITAM_CHECK_LOGBOOK_OPERATION_APP;
}
