debug: false

spring:
  config:
    use-legacy-processing: true
  profiles:
    active: dev, swagger
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

  cloud:
    consul: #disabled for dev
      enabled: false
      discovery:
        enabled: false
        register: false
  data:
    mongodb:
      uri: mongodb://mongod_dbuser_iam:mongod_dbpwd_iam@localhost:27018/iam?connectTimeoutMS=2000

server:
  host:
  port: 8083
  ssl:
    key-store: ../../../dev-deployment/environments/keystores/server/localhost/keystore_iam.jks
    key-store-password: changeme
    key-password: changeme
    trust-store: ../../../dev-deployment/environments/keystores/server/truststore_server.jks
    trust-store-password: changeme
    client-auth: need
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384
  error:
    path: /error

management:
  server:
    address: localhost
    port: 8183
    ssl:
      enabled: false

iam:
  security-client:
    server-host: localhost
    server-port: 8084
    secure: false

cas-client:
  server-host: dev.vitamui.com
  server-port: 8080
  secure: true
  ssl-configuration:
    truststore:
      key-path: ../../../dev-deployment/environments/keystores/server/truststore_server.jks
      key-password: changeme
    keystore:
      key-path: ../../../dev-deployment/environments/keystores/server/localhost/keystore_iam.jks
      key-password: changeme
      type: JKS
    hostname-verification: false

cas.reset.password.url: /cas/extras/resetPassword?username={username}&firstname={firstname}&lastname={lastname}&language={language}&customerId={customerId}&ttl=1day

login:
  url: http://dev.vitamui.com:8080/cas/login
  attempts:
    maximum.failures: 5
    time.interval: 20

logbook:
  scheduling:
    enabled: false
    sendEventToVitamTasks:
      delay: 10000

vitam.tenant.init.mandatory: true

customer.init.config.file: src/main/resources/dev/customer-init.yml

user.connection.tracing.enabled: false

# Jaeger
opentracing:
  jaeger:
    enabled: true
    logSpans: true
    expandExceptionLogs: true
    udp-sender:
      host: localhost
      port: 6831

logging:
  level:
    fr.gouv.vitamui: DEBUG
    fr.gouv.vitamui.iam.security: DEBUG
    fr.gouv.vitamui.commons.mongo.service: DEBUG
    fr.gouv.vitamui.iam.server: DEBUG
    fr.gouv.vitamui.commons.logbook.scheduler: DEBUG
    # org.springframework.data.mongodb.core.MongoTemplate: DEBUG

gdpr_alert_readonly: true

provisioning-client:
  identity-providers:
    - idp-identifier: system_idp
      uri: "http://localhost:1080/provisioning/v1/users"
      client:
        secure: false
        ssl-configuration:
          keystore:
            key-path: ../../../dev-deployment/environments/keystores/server/localhost/keystore_iam.jks
            key-password: changeme
            type: JKS
          truststore:
            key-path: ../../../dev-deployment/environments/keystores/server/truststore_server.jks
            key-password: changeme
            type: JKS
          hostname-verification: false
    - idp-identifier: 2
      uri: https://localhost:8090/provisioning/v1/users
      client:
        secure: true
        ssl-configuration:
          keystore:
            key-path: ../../../dev-deployment/environments/keystores/server/localhost/keystore_iam.jks
            key-password: changeme
            type: JKS
          truststore:
            key-path: ../../../dev-deployment/environments/keystores/server/truststore_server.jks
            key-password: changeme
            type: JKS
          hostname-verification: false

address:
  max-street-length: 250

# Password configuration
password:
  max-old-password: 12

---
spring:
  config:
    activate:
      on-profile: gateway

gateway:
  enabled: true
server:
  ssl:
    client-auth: want
    client-certificate-header-name: x-ssl-cert

cas:
  external-url: https://dev.vitamui.com:8080/cas

list-enable-external-identifiers:
  tenants:
    0:
      - INGEST_CONTRACT
      - ACCESS_CONTRACT
      - MANAGEMENT_CONTRACT
      - ARCHIVE_UNIT_PROFILE
    1:
      - INGEST_CONTRACT
      - ACCESS_CONTRACT
      - MANAGEMENT_CONTRACT
      - PROFILE
      - SECURITY_PROFILE
      - CONTEXT
