# TECHNICAL PROPERTIES / DON'T put environment properties
# This property can be override by a config file give at run time with spring.config.location

spring:
  application:
    name: iam
    version: '@project.version@'
  api:
    name: API IAM (Identity Access Management)
    description: This API is used to manage customers, tenants, identity providers, users with their profiles and their profiles groups.
    version: v1
  jmx:
    unique-names: true

management:
  endpoints:
    jmx:
      domain: iam
    web.exposure.include: '*'
  endpoint:
    health:
      show-details: always

swagger:
  layer: api-external
  file-path: file:../../../tools/swagger/docs/api-external/iam/swagger.json

metrics:
  reporterInterval: 1
  reporterIntervalUnit: MINUTES
  index: metrics-vitam-jvm

# Tokens TTL
token.max-ttl: 480 # 8 (hours) * 60 (minutes)
token.ttl: 240 # 4 (hours) * 60 (minutes)
token.additional.ttl: 15
subrogaton.token.ttl: 165
api.token.ttl: 480
generic.users.subrogation.ttl: 180
subrogation.ttl: 30

cas.reset.password.url: /extras/resetPassword?username={username}&firstname={firstname}&lastname={lastname}&language={language}&customerId={customerId}&ttl=1day

user.connection.tracing.enabled: false

gateway:
  enabled: true
