---

- block:

    - name: Uninstall old JDK packages
      package:
        name:
          - "{{ 'openjdk-8-jre-headless' if ansible_os_family == 'Debian' else 'java-1.8.0-openjdk-headless' }}"
          - "{{ 'openjdk-11-jre-headless' if ansible_os_family == 'Debian' else 'java-11-openjdk-headless' }}"
          - "{{ 'openjdk-17-jre-headless' if ansible_os_family == 'Debian' else 'java-17-openjdk-headless' }}"
        state: absent
      register: result
      retries: "{{ packages_install_retries_number | default(2) }}"
      until: result is succeeded
      delay: "{{ packages_install_retries_delay | default(10) }}"

    - name: Install JDK 21
      package:
        name: "{{ 'jdk-21' if ansible_os_family == 'Debian' else 'java-21-openjdk-headless' }}"
        state: latest
      register: result
      retries: "{{ packages_install_retries_number }}"
      until: result is succeeded
      delay: "{{ packages_install_retries_delay }}"

  when:
    - install_mode != "container"
