<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <groupId>fr.gouv.vitamui</groupId>
    <artifactId>parent</artifactId>
    <version>8.1.21-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>VITAMUI</name>
    <description>${project.artifactId}</description>

    <organization>
        <name>VITAMUI Team</name>
    </organization>

    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <!-- Modules -->
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

    <modules>
        <module>bom</module>
        <module>commons</module>
        <module>api</module>
        <module>cas</module>
        <module>deployment</module>
        <module>packaging</module>
        <module>cots</module>
    </modules>

    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <!-- Définition des SCM, ciManagement -->
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->

    <!-- Définition de l'url du gestionnaire de source Ã utiliser -->
    <scm>
        <connection>scm:git:https://github.com/vitam-prg/vitamUI.git</connection>
        <developerConnection>scm:git:https://github.com/vitam-prg/vitamUI.git</developerConnection>
        <url>https://github.com/vitam-prg/vitamUI.git</url>
        <tag>HEAD</tag>
    </scm>

    <repositories>
        <!-- <id>vitam</id> to be defined in Profiles -->
    </repositories>
    <distributionManagement>
        <!-- <id>vitam</id> to be defined in Profiles -->
    </distributionManagement>

    <!-- Définition de l'url de l'intégration continue du projet -->
    <!-- <ciManagement> <system>jenkins</system> <url>https://dev.vitamui.com/jenkins/</url>
    </ciManagement> -->

    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <!-- Définition des properties -->
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <properties>
        <!-- Global Properties -->
        <maven.build.timestamp.format>yyyyMMdd_HHmm</maven.build.timestamp.format>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>21</java.version>
        <java.release>21</java.release>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.release>21</maven.compiler.release>

        <vitam.version>8.1.0-SNAPSHOT</vitam.version>

        <!-- Web Pack -->
        <node.version>v18.20.3</node.version>
        <npm.version>10.7.0</npm.version>

        <!--Spring dependencies version override-->
        <!--Snakeyaml version override to 2.x to fix CVE-2022-1471-->
        <snakeyaml.version>2.4</snakeyaml.version>

        <!-- override it to fix mockito java 21 issue -->

        <byte-buddy.version>1.15.5</byte-buddy.version>
        <!--Plugins version -->
        <asciidoctorj.pdf.version>1.5.4</asciidoctorj.pdf.version>
        <jruby.complete.version>9.2.13.0</jruby.complete.version>
        <launch4j-maven-plugin.version>2.4.1</launch4j-maven-plugin.version>
        <license-maven-plugin.version>3.0</license-maven-plugin.version>
        <lombok.version>1.18.30</lombok.version>
        <jib-maven-plugin.version>3.4.2</jib-maven-plugin.version>
        <maven.antrun.plugin.version>1.8</maven.antrun.plugin.version>
        <maven.asciidoctor.plugin.version>2.0.0</maven.asciidoctor.plugin.version>
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <maven.dependencycheck.version>6.1.1</maven.dependencycheck.version>
        <maven.deploy.plugin.version>2.8.2</maven.deploy.plugin.version>
        <maven.exec.plugin.version>1.6.0</maven.exec.plugin.version>
        <maven.directory.plugin.version>0.1</maven.directory.plugin.version>
        <maven.failsafe.plugin.version>2.21.0</maven.failsafe.plugin.version>
        <maven.filtering.plugin.version>3.4.0</maven.filtering.plugin.version>
        <maven.spotbugs.plugin.version>4.0.4</maven.spotbugs.plugin.version>
        <maven.frontend.plugin.version>1.6</maven.frontend.plugin.version>
        <maven.jacoco.plugin.version>0.8.12</maven.jacoco.plugin.version>
        <maven.jar.plugin.version>3.0.2</maven.jar.plugin.version>
        <maven.javadoc.plugin.version>3.0.0</maven.javadoc.plugin.version>
        <maven.jaxb2.plugin.version>2.5.0</maven.jaxb2.plugin.version>
        <maven.lombok.plugin.version>1.18.20.0</maven.lombok.plugin.version>
        <maven.pmd.plugin.version>3.13.0</maven.pmd.plugin.version>
        <maven.project.info.reports.plugin.version>3.0.0</maven.project.info.reports.plugin.version>
        <maven.release.plugin.version>2.5.3</maven.release.plugin.version>
        <maven.resources.plugin.version>3.3.1</maven.resources.plugin.version>
        <maven.site.plugin.version>3.9.1</maven.site.plugin.version>
        <maven.sonar.plugin.version>3.4.0.905</maven.sonar.plugin.version>
        <maven.source.plugin.version>3.0.1</maven.source.plugin.version>
        <maven.surefire.plugin.version>3.1.2</maven.surefire.plugin.version>
        <maven.swagger2markup.plugin.version>1.3.3</maven.swagger2markup.plugin.version>
        <maven.war.plugin.version>3.2.0</maven.war.plugin.version>
        <maven.assembly.version>3.2.0</maven.assembly.version>
        <serenity.maven.plugin>3.3.10</serenity.maven.plugin>
        <spotless-maven-plugin.version>2.43.0</spotless-maven-plugin.version>
        <spotless-maven-plugin.prettier.version>3.2.4</spotless-maven-plugin.prettier.version>
        <spotless-maven-plugin.prettier-plugin-java.version>2.6.0</spotless-maven-plugin.prettier-plugin-java.version>

        <!-- Profile properties -->
        <rpm.jar-file>${project.build.finalName}.jar</rpm.jar-file>
        <!-- Put this properties to false sub-module when you want to use profile -->
        <rpm.skip>true</rpm.skip>
        <rpm.publication.env>dev</rpm.publication.env>
        <!-- Swagger doc generation -->
        <swagger.dir>.</swagger.dir>
        <swagger.skip>true</swagger.skip>
        <itCoverageAgent></itCoverageAgent>

        <cveUrlBase>${env.SERVICE_REPOSITORY_URL}/nist/nvdcve-1.1-%d.json.gz</cveUrlBase>
        <cveUrlModified>${env.SERVICE_REPOSITORY_URL}/nist/nvdcve-1.1-modified.json.gz</cveUrlModified>
    </properties>

    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <!-- Gestion des dépendances -->
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>bom</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <!-- Security check for dependencies -->
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>${maven.dependencycheck.version}</version>
                <inherited>false</inherited>
                <configuration>
                    <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                    <retireJsAnalyzerEnabled>false</retireJsAnalyzerEnabled>
                    <failOnError>false</failOnError>
                </configuration>

                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${license-maven-plugin.version}</version>
                <inherited>false</inherited>
                <configuration>
                    <header>LICENSE.txt</header>
                    <properties>
                        <owner>VITAM UI</owner>
                        <email>contact@programmevitam.fr</email>
                    </properties>
                    <includes>
                        <include>**/src/main/java/**</include>
                        <include>**/*.ts</include>
                    </includes>
                    <excludes>
                        <exclude>**/org/apereo/cas/**</exclude>
                        <exclude>**/node_modules/**</exclude>
                        <exclude>**/target/**</exclude>
                        <exclude>**/dist/**</exclude>
                        <exclude>**/.directory/**</exclude>
                        <exclude>**/cas-server/src/main/resources/**</exclude>
                    </excludes>
                    <mapping>
                        <ts>SLASHSTAR_STYLE</ts>
                    </mapping>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>${maven.release.plugin.version}</version>
                <configuration>
                    <tagNameFormat>@{project.version}</tagNameFormat>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>${maven.resources.plugin.version}</version>
                <configuration>
                    <nonFilteredFileExtensions>
                        <nonFilteredFileExtension>jks</nonFilteredFileExtension>
                        <nonFilteredFileExtension>p12</nonFilteredFileExtension>
                        <nonFilteredFileExtension>pem</nonFilteredFileExtension>
                    </nonFilteredFileExtensions>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.shared</groupId>
                        <artifactId>maven-filtering</artifactId>
                        <version>${maven.filtering.plugin.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
            <!-- Directory plugin to find parent root directory absolute path -->
            <plugin>
                <groupId>org.commonjava.maven.plugins</groupId>
                <artifactId>directory-maven-plugin</artifactId>
                <version>${maven.directory.plugin.version}</version>
                <executions>
                    <execution>
                        <id>directories</id>
                        <goals>
                            <goal>highest-basedir</goal>
                        </goals>
                        <phase>initialize</phase>
                        <configuration>
                            <property>main.basedir</property>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless-maven-plugin.version}</version>
                <configuration>
                    <java>
                        <includes>
                            <include>src/main/java/**/*.java</include>
                            <include>src/test/java/**/*.java</include>
                        </includes>
                        <prettier>
                            <devDependencies>
                                <prettier>${spotless-maven-plugin.prettier.version}</prettier>
                                <prettier-plugin-java>${spotless-maven-plugin.prettier-plugin-java.version}
                                </prettier-plugin-java>
                            </devDependencies>
                            <config>
                                <printWidth>120</printWidth>
                                <tabWidth>4</tabWidth>
                                <parser>java</parser>
                                <plugins>prettier-plugin-java</plugins>
                            </config>
                        </prettier>
                        <importOrder>
                            <order>,javax|java,\#</order>
                        </importOrder>
                        <removeUnusedImports/>
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                    <configuration>
                        <from>
                            <!--<image>gcr.io/distroless/java11-debian11</image>-->
                            <image>gcr.io/distroless/java21</image>
                        </from>
                        <allowInsecureRegistries>true</allowInsecureRegistries>
                        <container>
                            <jvmFlags>
                                <jvmFlag>-XX:MaxRAMPercentage=75.0</jvmFlag>
                                <jvmFlag>-XX:MinRAMPercentage=50.0</jvmFlag>
                                <jvmFlag>-XX:+ExitOnOutOfMemoryError</jvmFlag>
                            </jvmFlags>
                            <labels>
                                <!--  <git.commit.id>${git.commit.id}</git.commit.id>-->
                                <mvn.build.version>${project.version}</mvn.build.version>
                            </labels>
                        </container>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>build</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven.source.plugin.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                        <forceJavacCompilerUse>true</forceJavacCompilerUse>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>org.projectlombok</groupId>
                                <artifactId>lombok</artifactId>
                                <version>${lombok.version}</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>${maven.assembly.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven.javadoc.plugin.version}</version>
                </plugin>
                <plugin>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>${maven.deploy.plugin.version}</version>
                </plugin>
                <!-- find bugs in current project -->
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>${maven.spotbugs.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-pmd-plugin</artifactId>
                    <version>${maven.pmd.plugin.version}</version>
                    <configuration>
                        <rulesets>
                            <ruleset>${main.basedir}/pmd-rulesets.xml</ruleset>
                        </rulesets>
                        <failOnViolation>false</failOnViolation>
                    </configuration>
                </plugin>
                <plugin>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven.jar.plugin.version}</version>
                    <configuration>
                        <!-- Supprimer l'option classifier -->
                        <classifier></classifier>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>${maven.site.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>${maven.project.info.reports.plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven.surefire.plugin.version}</version>
                </plugin>
                <plugin>
                    <!-- The Surefire Report Plugin parses the generated TEST-*.xml files
                         under ${basedir}/target/surefire-reports and renders them to DOXIA which
                        creates the web interface version of the test results. -->
                    <artifactId>maven-surefire-report-plugin</artifactId>
                    <version>${maven.surefire.plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven.failsafe.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>${maven.antrun.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <configuration>
                        <addResources>false</addResources>
                        <jvmArguments>-Xmx512m</jvmArguments>
                        <additionalProperties>
                            <version.release>${project.version}</version.release>
                        </additionalProperties>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <configuration>
                        <failOnMissingWebXml>false</failOnMissingWebXml>
                    </configuration>
                    <version>${maven.war.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.projectlombok</groupId>
                    <artifactId>lombok-maven-plugin</artifactId>
                    <version>${maven.lombok.plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>generate-sources</phase>
                            <goals>
                                <goal>delombok</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>${maven.sonar.plugin.version}</version>
                    <executions>
                        <execution>
                            <phase>verify</phase>
                            <goals>
                                <goal>sonar</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>${maven.jacoco.plugin.version}</version>
                    <executions>
                        <execution>
                            <id>default-prepare-agent</id>
                            <goals>
                                <goal>prepare-agent</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>jacoco-site</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>report</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>exec-maven-plugin</artifactId>
                    <version>${maven.exec.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>net.serenity-bdd.maven.plugins</groupId>
                    <artifactId>serenity-maven-plugin</artifactId>
                    <version>${serenity.maven.plugin}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.mojo</groupId>
                    <artifactId>jaxb2-maven-plugin</artifactId>
                    <version>${maven.jaxb2.plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-pmd-plugin</artifactId>
                <configuration>
                    <rulesets>
                        <ruleset>${maven.multiModuleProjectDirectory}/pmd-rulesets.xml</ruleset>
                    </rulesets>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <reportSets>
                    <reportSet>
                        <reports>
                            <!-- select non-aggregate reports -->
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>
            </plugin>
        </plugins>
    </reporting>

    <profiles>
        <profile>
            <id>no-cve-proxy</id>
            <properties>
                <cveUrlBase>https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-%d.json.gz</cveUrlBase>
                <cveUrlModified>https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-modified.json.gz</cveUrlModified>
            </properties>
        </profile>

        <!-- This profile is used to build frontend project for dev purposes. -->
        <profile>
            <id>dev</id>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                    </resource>
                    <resource>
                        <directory>target/www/</directory>
                        <targetPath>static/</targetPath>
                    </resource>
                </resources>
            </build>
        </profile>

        <!-- This profile is used to build frontend project for prod purposes. -->
        <profile>
            <id>prod</id>
            <properties>
                <rpm.publication.env>stable</rpm.publication.env>
            </properties>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                        <excludes>
                            <!-- Vitam configuration files -->
                            <exclude>*.conf</exclude>
                            <exclude>/dev/</exclude>
                            <exclude>application-*.yml</exclude>
                        </excludes>
                    </resource>
                    <resource>
                        <directory>target/www/</directory>
                        <targetPath>static/</targetPath>
                    </resource>
                </resources>
            </build>
        </profile>

        <!-- This profile is used to build rpm package.-->
        <profile>
            <id>rpm</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>rpm-package</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>make</executable>
                                    <workingDirectory>target</workingDirectory>
                                    <skip>${rpm.skip}</skip>
                                    <arguments>
                                        <argument>-f</argument>
                                        <argument>${main.basedir}/tools/packaging/Makefile</argument>
                                        <argument>rpm</argument>
                                        <argument>NAME=${project.artifactId}</argument>
                                        <argument>VERSION=${project.version}</argument>
                                        <argument>JAR_FILE=${rpm.jar-file}</argument>
                                        <!-- If you want to changes default dependencies (only
                                        systemd),
                                        define them as a comma separated list of packages -->
                                        <argument>DEPENDENCIES=systemd,java-21-openjdk</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

                </plugins>
            </build>
        </profile>

        <!-- TEST DEB WITH FPM -->
        <profile>
            <id>deb</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>deb-package</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>make</executable>
                                    <workingDirectory>target</workingDirectory>
                                    <skip>${rpm.skip}</skip>
                                    <arguments>
                                        <argument>-f</argument>
                                        <argument>${main.basedir}/tools/packaging/Makefile</argument>
                                        <argument>deb</argument>
                                        <argument>NAME=${project.artifactId}</argument>
                                        <argument>VERSION=${project.version}</argument>
                                        <argument>JAR_FILE=${rpm.jar-file}</argument>
                                        <!-- If you want to changes default dependencies (only
                                        systemd),
                                        define them as a comma separated list of packages -->
                                        <argument>DEPENDENCIES=systemd</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- This profile is used to generate sonar-metrics sonar informations.-->
        <profile>
            <id>sonar-metrics</id>
            <build>
                <resources>
                    <resource>
                        <directory>src/main/resources</directory>
                    </resource>
                    <resource>
                        <directory>target/www/</directory>
                        <targetPath>static/</targetPath>
                    </resource>
                </resources>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>@{argLine}</argLine>
                        </configuration>
                    </plugin>
                    <plugin>
                        <groupId>com.github.spotbugs</groupId>
                        <artifactId>spotbugs-maven-plugin</artifactId>
                        <version>${maven.spotbugs.plugin.version}</version>
                        <configuration>
                            <failOnError>false</failOnError>
                        </configuration>
                        <executions>
                            <execution>
                                <id>check</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-pmd-plugin</artifactId>
                        <configuration>
                            <rulesets>
                                <ruleset>${main.basedir}/pmd-rulesets.xml</ruleset>
                            </rulesets>
                        </configuration>
                        <executions>
                            <execution>
                                <id>check</id>
                                <phase>test</phase>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                    </plugin>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>${maven.dependencycheck.version}</version>
                        <configuration>
                            <formats>
                                <format>XML</format>
                                <format>HTML</format>
                                <format>JSON</format>
                            </formats>
                        </configuration>
                        <executions>
                            <execution>
                                <id>default-cli</id>
                                <goals>
                                    <goal>aggregate</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <!-- Set project configuration file for test coverage -->
                <angular.additional.test.informations>
                    --karma-config=${main.basedir}/ui/ui-frontend/projects/${angular.build.project}/karma.conf.ci.js
                </angular.additional.test.informations>
                <maven.test.failure.ignore>true</maven.test.failure.ignore>
            </properties>
        </profile>
        <!-- This profile is used to update sonar informations.-->
        <profile>
            <id>sonar</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonarsource.scanner.maven</groupId>
                        <artifactId>sonar-maven-plugin</artifactId>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <sonar.core.codeCoveragePlugin>jacoco</sonar.core.codeCoveragePlugin>
                <sonar.coverage.exclusions>**/*Dto.java, **/domain/*.java, **/vitam/seda/*.java,
                    **/*spec.ts, **/*.scss,
                    **/*.css
                </sonar.coverage.exclusions>
                <sonar.cpd.exclusions>**/*Dto.java, **/domain/*.java, **/*spec.ts</sonar.cpd.exclusions>
                <sonar.exclusions>**/node_modules/**, **/sass/**</sonar.exclusions>
                <sonar.java.spotbugs.reportPaths>./target/spotbugsXml.xml</sonar.java.spotbugs.reportPaths>
                <sonar.java.pmd.reportPaths>./target/pmd.xml</sonar.java.pmd.reportPaths>
                <sonar.dependencyCheck.htmlReportPath>./target/dependency-check-report.html
                </sonar.dependencyCheck.htmlReportPath>
                <sonar.dependencyCheck.jsonReportPath>./target/dependency-check-report.json
                </sonar.dependencyCheck.jsonReportPath>
                <sonar.dependencyCheck.xmlReportPath>./target/dependency-check-report.xml
                </sonar.dependencyCheck.xmlReportPath>
                <!-- TODO: This properties need to bo specify by the user who execute
                the report (ex: Jenkins or developper) -->
                <sonar.host.url/>
                <!-- TODO: This properties need to bo specify by the user who execute
                the report (ex: Jenkins or developper) -->
                <sonar.login/>
                <sonar.typescript.lcov.reportPaths>
                    ${main.basedir}/ui/ui-frontend/target/coverage/commons/lcov.info,${main.basedir}/ui/ui-frontend/target/coverage/flow/lcov.info,${main.basedir}/ui/ui-frontend/target/coverage/identity/lcov.info,${main.basedir}/ui/ui-frontend/target/coverage/portal/lcov.info
                </sonar.typescript.lcov.reportPaths>
            </properties>

        </profile>

        <!-- This profile is used to generate swagger documentation. -->
        <profile>
            <id>swagger</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <test>SwaggerJsonFileGenerationTest.java</test>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!-- This profile is used to generate swagger documentation. -->
        <profile>
            <id>swagger-docs</id>
            <build>
                <plugins>

                    <plugin>
                        <groupId>io.github.swagger2markup</groupId>
                        <artifactId>swagger2markup-maven-plugin</artifactId>
                        <version>${maven.swagger2markup.plugin.version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>io.github.swagger2markup</groupId>
                                <artifactId>swagger2markup-import-files-ext</artifactId>
                                <version>${maven.swagger2markup.plugin.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>io.github.swagger2markup</groupId>
                                <artifactId>swagger2markup-spring-restdocs-ext</artifactId>
                                <version>${maven.swagger2markup.plugin.version}</version>
                            </dependency>
                        </dependencies>
                        <configuration>
                            <swaggerInput>
                                ${main.basedir}/tools/swagger/docs/${swagger.dir}/${project.artifactId}/swagger.json
                            </swaggerInput>
                            <outputDir>${project.build.directory}/generated-sources/swagger/</outputDir>
                            <config>
                                <swagger2markup.markupLanguage>ASCIIDOC</swagger2markup.markupLanguage>
                                <swagger2markup.outputLanguage>FR</swagger2markup.outputLanguage>
                                <swagger2markup.generatedExamplesEnabled>TRUE</swagger2markup.generatedExamplesEnabled>
                                <swagger2markup.pathsGroupedBy>TAGS</swagger2markup.pathsGroupedBy>
                            </config>
                            <skip>${swagger.skip}</skip>
                        </configuration>
                        <executions>
                            <execution>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>convertSwagger2markup</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.asciidoctor</groupId>
                        <artifactId>asciidoctor-maven-plugin</artifactId>
                        <version>${maven.asciidoctor.plugin.version}</version>
                        <dependencies>
                            <dependency>
                                <groupId>org.asciidoctor</groupId>
                                <artifactId>asciidoctorj-pdf</artifactId>
                                <version>${asciidoctorj.pdf.version}</version>
                            </dependency>
                            <dependency>
                                <groupId>org.jruby</groupId>
                                <artifactId>jruby-complete</artifactId>
                                <version>${jruby.complete.version}</version>
                            </dependency>
                        </dependencies>
                        <configuration>
                            <sourceDirectory>${main.basedir}/tools/swagger/config/</sourceDirectory>
                            <sourceDocumentName>index.adoc</sourceDocumentName>
                            <backend>html5</backend>
                            <outputDirectory>
                                ${main.basedir}/tools/swagger/docs/${swagger.dir}/${project.artifactId}
                            </outputDirectory>
                            <attributes>
                                <toc>left</toc>
                                <toclevels>3</toclevels>
                                <numbered></numbered>
                                <hardbreaks></hardbreaks>
                                <sectlinks></sectlinks>
                                <sectanchors></sectanchors>
                                <generated>${project.build.directory}/generated-sources/swagger/</generated>
                            </attributes>
                            <skip>${swagger.skip}</skip>
                        </configuration>
                        <executions>
                            <execution>
                                <id>output-html</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                            </execution>
                            <execution>
                                <id>output-pdf</id>
                                <phase>generate-resources</phase>
                                <goals>
                                    <goal>process-asciidoc</goal>
                                </goals>
                                <configuration>
                                    <backend>pdf</backend>
                                    <outputDirectory>
                                        ${main.basedir}/tools/swagger/docs/${swagger.dir}/${project.artifactId}
                                    </outputDirectory>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <!-- Repositories used for swagger doc generation  -->
            <pluginRepositories>
                <pluginRepository>
                    <id>jcenter-snapshots</id>
                    <name>jcenter</name>
                    <url>https://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
                </pluginRepository>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>jcenter-releases</id>
                    <name>jcenter</name>
                    <url>https://jcenter.bintray.com</url>
                </pluginRepository>
            </pluginRepositories>
        </profile>

        <profile>
            <!-- Profile to use for all Vitam internal developers -->
            <id>vitam</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <!-- Dépôts Maven privés -->
            <distributionManagement>
                <repository>
                    <id>vitam-releases</id>
                    <name>Vitam release repository</name>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-releases/</url>
                </repository>
                <snapshotRepository>
                    <id>vitam-snapshots</id>
                    <name>Vitam SNAPSHOT repository</name>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-snapshots/</url>
                </snapshotRepository>
                <site>
                    <id>${project.artifactId}-site</id>
                    <url>${project.baseUri}</url>
                </site>
            </distributionManagement>

            <repositories>
                <repository>
                    <id>vitam-releases</id>
                    <name>Vitam release repository</name>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-releases/</url>
                </repository>
                <repository>
                    <id>vitam-snapshots</id>
                    <name>Vitam SNAPSHOT repository</name>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-snapshots/</url>
                </repository>
            </repositories>

            <properties>
                <serverId>vitam</serverId>
                <downloadRoot>${env.SERVICE_NEXUS_URL}/repository/node-distrib/</downloadRoot>
            </properties>
        </profile>

        <profile>
            <!-- Profile to use for all Vitam internal developers -->
            <id>vitam-external</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <!-- Dépôts publics de releases -->
            <repositories>
                <repository>
                    <id>public-vitam-releases</id>
                    <url>http://download.programmevitam.fr/vitam_repository/${vitam.version}/mvn_repo/</url>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                </repository>
            </repositories>

        </profile>

    </profiles>

</project>
