---

- name: "Install static ressources for {{ vitamui_struct.vitamui_component }}"
  package:
    name: "{{ vitamui_struct.package_name | default(package_name) }}"
    state: latest
  register: package_installed
  retries: "{{ packages_install_retries_number }}"
  until: package_installed is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags: update_vitamui_package
  notify: reload nginx

- name: Install static ressources for ui-identity-admin - Copy folder
  command:
    cmd: cp -va "{{ frontend_data_dir }}/ui-identity/." "{{ frontend_data_dir }}/ui-identity-admin"
  when: vitamui_struct.vitamui_component == "ui-identity-admin"

- name: Get package facts
  package_facts:
  register: package_facts_result
  no_log: "{{ hide_passwords_during_deploy }}"

- name: Get application version from package
  set_fact:
    frontend_application_version: "{{ package_facts_result.ansible_facts.packages[ vitamui_struct.package_name | default(package_name) ][0].version }}"

- name: Configure upstream for API GW
  template:
    src: frontend/upstream_gw.j2
    dest: "{{ nginx_conf_dir }}/upstream_gw"
    group: "{{ frontend_group }}"
    owner: "{{ frontend_user }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  notify: reload nginx

- name: Add config.json file
  template:
    src: frontend/config.json.j2
    dest: "{{ frontend_data_dir }}/{{ vitamui_struct.vitamui_component }}/assets/config.json"
    group: "{{ frontend_group }}"
    owner: "{{ frontend_user }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  notify: reload nginx

- name: "Configure vhost for {{ vitamui_struct.vitamui_component }}"
  template:
    src: frontend/vhost.conf.j2
    dest: "{{ nginx_conf_dir }}/{{ vitamui_struct.vitamui_component }}.conf"
    group: "{{ frontend_group }}"
    owner: "{{ frontend_user }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  notify: reload nginx

- name: "Add client certificates for {{ vitamui_struct.vitamui_component }}"
  copy:
    src: "{{ inventory_dir }}/certs/vitamui-services/clients/{{ vitamui_struct.vitamui_component }}/{{ vitamui_struct.vitamui_component }}.{{ item }}"
    dest: "{{ nginx_ssl_dir }}/{{ vitamui_struct.vitamui_component }}_client.{{ item }}"
    group: "{{ frontend_group }}"
    owner: "{{ frontend_user }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  loop:
    - crt
    - key
  when: vitamui_struct.vitamui_component != "ui-design-system"
  tags: update_vitamui_certificates
  notify: reload nginx

- block:

    - name: "Add server certificates for {{ vitamui_struct.vitamui_component }} when secure is enabled"
      copy:
        src: "{{ inventory_dir }}/certs/vitamui-services/server/{{ vitamui_struct.vitamui_component }}/{{ vitamui_struct.vitamui_component }}.{{ item }}"
        dest: "{{ nginx_ssl_dir }}/{{ vitamui_struct.vitamui_component }}_server.{{ item }}"
        group: "{{ frontend_group }}"
        owner: "{{ frontend_user }}"
        mode: "{{ vitam_defaults.folder.conf_permission }}"
      loop:
        - crt
        - key
      tags: update_vitamui_certificates
      notify: reload nginx

    - name: "Put ssl configuration for {{ vitamui_struct.vitamui_component }} when secure is enabled"
      template:
        src: ssl-ui.conf.j2
        dest: "{{ nginx_ssl_dir }}/{{ vitamui_struct.vitamui_component }}-ssl.conf"
        group: "{{ frontend_group }}"
        owner: "{{ frontend_user }}"
        mode: "{{ vitamui_defaults.folder.conf_permission }}"
      notify: reload nginx

  when: vitamui_struct.secure | default(secure) | bool

- name: Ensure nginx is started
  systemd:
    name: nginx
    state: started

#### Consul configuration ####
- name: "Deploy consul agent service declaration for {{ vitamui_struct.vitamui_component }} service"
  template:
    src: service-componentid.json.j2
    dest: "{{ consul.conf_folder | default(consul_folder_conf) }}/service-{{ vitamui_struct.vitamui_component }}.json"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ '0644' if install_mode == 'container' else vitam_defaults.folder.conf_permission }}"
  tags: consul_conf
  notify: nginx_webapp - reload consul configuration
