/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//

package fr.gouv.vitamui.commons.vitam.seda;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ArchiveTransferType complex type. <p>The following schema
 * fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ArchiveTransferType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{fr:gouv:culture:archivesdefrance:seda:v2.1}BusinessRequestMessageType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RelatedTransferReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="TransferRequestReplyIdentifier" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType" minOccurs="0"/&gt;
 *         &lt;element name="ArchivalAgency" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}OrganizationWithIdType"/&gt;
 *         &lt;element name="TransferringAgency" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}OrganizationWithIdType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArchiveTransferType", propOrder = { "relatedTransferReference", "transferRequestReplyIdentifier",
        "archivalAgency", "transferringAgency" })
@XmlRootElement(name = "ArchiveTransfer")
public class ArchiveTransferType extends BusinessRequestMessageType {

    @XmlElement(name = "RelatedTransferReference")
    protected List<IdentifierType> relatedTransferReference;

    @XmlElement(name = "TransferRequestReplyIdentifier")
    protected IdentifierType transferRequestReplyIdentifier;

    @XmlElement(name = "ArchivalAgency", required = true)
    protected OrganizationWithIdType archivalAgency;

    @XmlElement(name = "TransferringAgency", required = true)
    protected OrganizationWithIdType transferringAgency;

    /**
     * Gets the value of the relatedTransferReference property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedTransferReference property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedTransferReference().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     *
     *
     */
    public List<IdentifierType> getRelatedTransferReference() {
        if (relatedTransferReference == null) {
            relatedTransferReference = new ArrayList<>();
        }
        return relatedTransferReference;
    }

    /**
     * Gets the value of the transferRequestReplyIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *
     */
    public IdentifierType getTransferRequestReplyIdentifier() {
        return transferRequestReplyIdentifier;
    }

    /**
     * Sets the value of the transferRequestReplyIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *
     */
    public void setTransferRequestReplyIdentifier(IdentifierType value) {
        transferRequestReplyIdentifier = value;
    }

    /**
     * Gets the value of the archivalAgency property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationWithIdType }
     *
     */
    public OrganizationWithIdType getArchivalAgency() {
        return archivalAgency;
    }

    /**
     * Sets the value of the archivalAgency property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationWithIdType }
     *
     */
    public void setArchivalAgency(OrganizationWithIdType value) {
        archivalAgency = value;
    }

    /**
     * Gets the value of the transferringAgency property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationWithIdType }
     *
     */
    public OrganizationWithIdType getTransferringAgency() {
        return transferringAgency;
    }

    /**
     * Sets the value of the transferringAgency property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationWithIdType }
     *
     */
    public void setTransferringAgency(OrganizationWithIdType value) {
        transferringAgency = value;
    }

}
