/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//

package fr.gouv.vitamui.commons.vitam.seda;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Unité de base des métadonnées de description contenant la gestion de
 * l'arborescence. <p>Java class for ArchiveUnitType complex type. <p>The
 * following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ArchiveUnitType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="ArchiveUnitRefId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitRefIdType"/&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="ArchiveUnitProfile" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType" minOccurs="0"/&gt;
 *           &lt;element name="Management" minOccurs="0"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ManagementGroup"/&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="Content" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DescriptiveMetadataContentType"/&gt;
 *           &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *             &lt;element name="ArchiveUnit" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitType"/&gt;
 *             &lt;element ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitReferenceAbstract"/&gt;
 *             &lt;element name="DataObjectReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefType"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="id" use="required" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitIdType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArchiveUnitType", propOrder = { "archiveUnitRefId", "archiveUnitProfile", "management", "content",
        "archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference" })
public class ArchiveUnitType {

    @XmlElement(name = "ArchiveUnitRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object archiveUnitRefId;

    @XmlElement(name = "ArchiveUnitProfile")
    protected IdentifierType archiveUnitProfile;

    @XmlElement(name = "Management")
    protected ArchiveUnitType.Management management;

    @XmlElement(name = "Content")
    protected DescriptiveMetadataContentType content;

    @XmlElements({ @XmlElement(name = "ArchiveUnit", type = ArchiveUnitType.class),
            @XmlElement(name = "ArchiveUnitReferenceAbstract"),
            @XmlElement(name = "DataObjectReference", type = DataObjectRefType.class) })
    protected List<Object> archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference;

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String id;

    /**
     * Gets the value of the archiveUnitRefId property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getArchiveUnitRefId() {
        return archiveUnitRefId;
    }

    /**
     * Sets the value of the archiveUnitRefId property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setArchiveUnitRefId(Object value) {
        archiveUnitRefId = value;
    }

    /**
     * Gets the value of the archiveUnitProfile property.
     *
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *
     */
    public IdentifierType getArchiveUnitProfile() {
        return archiveUnitProfile;
    }

    /**
     * Sets the value of the archiveUnitProfile property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *
     */
    public void setArchiveUnitProfile(IdentifierType value) {
        archiveUnitProfile = value;
    }

    /**
     * Gets the value of the management property.
     *
     * @return
     *     possible object is
     *     {@link ArchiveUnitType.Management }
     *
     */
    public ArchiveUnitType.Management getManagement() {
        return management;
    }

    /**
     * Sets the value of the management property.
     *
     * @param value
     *     allowed object is
     *     {@link ArchiveUnitType.Management }
     *
     */
    public void setManagement(ArchiveUnitType.Management value) {
        management = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return
     *     possible object is
     *     {@link DescriptiveMetadataContentType }
     *
     */
    public DescriptiveMetadataContentType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value
     *     allowed object is
     *     {@link DescriptiveMetadataContentType }
     *
     */
    public void setContent(DescriptiveMetadataContentType value) {
        content = value;
    }

    /**
     * Gets the value of the archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArchiveUnitType }
     * {@link Object }
     * {@link DataObjectRefType }
     *
     *
     */
    public List<Object> getArchiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference() {
        if (archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference == null) {
            archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference = new ArrayList<>();
        }
        return archiveUnitOrArchiveUnitReferenceAbstractOrDataObjectReference;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        id = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ManagementGroup"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "storageRule", "appraisalRule", "accessRule", "disseminationRule", "reuseRule",
            "classificationRule", "logBook", "needAuthorization", "otherManagementAbstract", "updateOperation" })
    public static class Management {

        @XmlElement(name = "StorageRule")
        protected StorageRuleType storageRule;

        @XmlElement(name = "AppraisalRule")
        protected AppraisalRuleType appraisalRule;

        @XmlElement(name = "AccessRule")
        protected AccessRuleType accessRule;

        @XmlElement(name = "DisseminationRule")
        protected DisseminationRuleType disseminationRule;

        @XmlElement(name = "ReuseRule")
        protected ReuseRuleType reuseRule;

        @XmlElement(name = "ClassificationRule")
        protected ClassificationRuleType classificationRule;

        @XmlElement(name = "LogBook")
        protected fr.gouv.vitamui.commons.vitam.seda.ManagementMetadataType.LogBook logBook;

        @XmlElement(name = "NeedAuthorization")
        protected Boolean needAuthorization;

        @XmlElement(name = "OtherManagementAbstract")
        protected List<Object> otherManagementAbstract;

        @XmlElement(name = "UpdateOperation")
        protected UpdateOperationType updateOperation;

        /**
         * Gets the value of the storageRule property.
         *
         * @return
         *     possible object is
         *     {@link StorageRuleType }
         *
         */
        public StorageRuleType getStorageRule() {
            return storageRule;
        }

        /**
         * Sets the value of the storageRule property.
         *
         * @param value
         *     allowed object is
         *     {@link StorageRuleType }
         *
         */
        public void setStorageRule(StorageRuleType value) {
            storageRule = value;
        }

        /**
         * Gets the value of the appraisalRule property.
         *
         * @return
         *     possible object is
         *     {@link AppraisalRuleType }
         *
         */
        public AppraisalRuleType getAppraisalRule() {
            return appraisalRule;
        }

        /**
         * Sets the value of the appraisalRule property.
         *
         * @param value
         *     allowed object is
         *     {@link AppraisalRuleType }
         *
         */
        public void setAppraisalRule(AppraisalRuleType value) {
            appraisalRule = value;
        }

        /**
         * Gets the value of the accessRule property.
         *
         * @return
         *     possible object is
         *     {@link AccessRuleType }
         *
         */
        public AccessRuleType getAccessRule() {
            return accessRule;
        }

        /**
         * Sets the value of the accessRule property.
         *
         * @param value
         *     allowed object is
         *     {@link AccessRuleType }
         *
         */
        public void setAccessRule(AccessRuleType value) {
            accessRule = value;
        }

        /**
         * Gets the value of the disseminationRule property.
         *
         * @return
         *     possible object is
         *     {@link DisseminationRuleType }
         *
         */
        public DisseminationRuleType getDisseminationRule() {
            return disseminationRule;
        }

        /**
         * Sets the value of the disseminationRule property.
         *
         * @param value
         *     allowed object is
         *     {@link DisseminationRuleType }
         *
         */
        public void setDisseminationRule(DisseminationRuleType value) {
            disseminationRule = value;
        }

        /**
         * Gets the value of the reuseRule property.
         *
         * @return
         *     possible object is
         *     {@link ReuseRuleType }
         *
         */
        public ReuseRuleType getReuseRule() {
            return reuseRule;
        }

        /**
         * Sets the value of the reuseRule property.
         *
         * @param value
         *     allowed object is
         *     {@link ReuseRuleType }
         *
         */
        public void setReuseRule(ReuseRuleType value) {
            reuseRule = value;
        }

        /**
         * Gets the value of the classificationRule property.
         *
         * @return
         *     possible object is
         *     {@link ClassificationRuleType }
         *
         */
        public ClassificationRuleType getClassificationRule() {
            return classificationRule;
        }

        /**
         * Sets the value of the classificationRule property.
         *
         * @param value
         *     allowed object is
         *     {@link ClassificationRuleType }
         *
         */
        public void setClassificationRule(ClassificationRuleType value) {
            classificationRule = value;
        }

        /**
         * Gets the value of the logBook property.
         *
         * @return
         *     possible object is
         *     {@link fr.gouv.vitamui.commons.vitam.seda.ManagementMetadataType.LogBook }
         *
         */
        public fr.gouv.vitamui.commons.vitam.seda.ManagementMetadataType.LogBook getLogBook() {
            return logBook;
        }

        /**
         * Sets the value of the logBook property.
         *
         * @param value
         *     allowed object is
         *     {@link fr.gouv.vitamui.commons.vitam.seda.ManagementMetadataType.LogBook }
         *
         */
        public void setLogBook(fr.gouv.vitamui.commons.vitam.seda.ManagementMetadataType.LogBook value) {
            logBook = value;
        }

        /**
         * Gets the value of the needAuthorization property.
         *
         * @return
         *     possible object is
         *     {@link Boolean }
         *
         */
        public Boolean isNeedAuthorization() {
            return needAuthorization;
        }

        /**
         * Sets the value of the needAuthorization property.
         *
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *
         */
        public void setNeedAuthorization(Boolean value) {
            needAuthorization = value;
        }

        /**
         * Autres métadonnées de gestion.Gets the value of the otherManagementAbstract property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the otherManagementAbstract property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOtherManagementAbstract().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         *
         *
         */
        public List<Object> getOtherManagementAbstract() {
            if (otherManagementAbstract == null) {
                otherManagementAbstract = new ArrayList<>();
            }
            return otherManagementAbstract;
        }

        /**
         * Gets the value of the updateOperation property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public UpdateOperationType getUpdateOperation() {
            return updateOperation;
        }

        /**
         * Sets the value of the updateOperation property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setUpdateOperation(UpdateOperationType value) {
            updateOperation = value;
        }

    }

}
