/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessMessageType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BusinessMessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{fr:gouv:culture:archivesdefrance:seda:v2.1}MessageType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ArchivalAgreement" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}IdentifierType" minOccurs="0"/&gt;
 *         &lt;element name="CodeListVersions" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}CodeListVersionsType"/&gt;
 *         &lt;element name="DataObjectPackage" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectPackageType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessMessageType", propOrder = {
    "archivalAgreement",
    "codeListVersions",
    "dataObjectPackage"
})
@XmlSeeAlso({
    BusinessRequestMessageType.class,
    BusinessReplyMessageType.class,
    BusinessNotificationMessageType.class
})
public abstract class BusinessMessageType
    extends MessageType
{

    @XmlElement(name = "ArchivalAgreement")
    protected IdentifierType archivalAgreement;
    @XmlElement(name = "CodeListVersions", required = true)
    protected CodeListVersionsType codeListVersions;
    @XmlElement(name = "DataObjectPackage")
    protected DataObjectPackageType dataObjectPackage;

    /**
     * Gets the value of the archivalAgreement property.
     *
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *
     */
    public IdentifierType getArchivalAgreement() {
        return archivalAgreement;
    }

    /**
     * Sets the value of the archivalAgreement property.
     *
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *
     */
    public void setArchivalAgreement(IdentifierType value) {
        this.archivalAgreement = value;
    }

    /**
     * Gets the value of the codeListVersions property.
     *
     * @return
     *     possible object is
     *     {@link CodeListVersionsType }
     *
     */
    public CodeListVersionsType getCodeListVersions() {
        return codeListVersions;
    }

    /**
     * Sets the value of the codeListVersions property.
     *
     * @param value
     *     allowed object is
     *     {@link CodeListVersionsType }
     *
     */
    public void setCodeListVersions(CodeListVersionsType value) {
        this.codeListVersions = value;
    }

    /**
     * Gets the value of the dataObjectPackage property.
     *
     * @return
     *     possible object is
     *     {@link DataObjectPackageType }
     *
     */
    public DataObjectPackageType getDataObjectPackage() {
        return dataObjectPackage;
    }

    /**
     * Sets the value of the dataObjectPackage property.
     *
     * @param value
     *     allowed object is
     *     {@link DataObjectPackageType }
     *
     */
    public void setDataObjectPackage(DataObjectPackageType value) {
        this.dataObjectPackage = value;
    }

}
