/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Métadonnées de base par type d'objet-données.
 *
 * <p>Java class for CoreMetadataType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CoreMetadataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Text" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}TextTechnicalMetadataType"/&gt;
 *         &lt;element name="Document" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DocumentTechnicalMetadataType"/&gt;
 *         &lt;element name="Image" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ImageTechnicalMetadataType"/&gt;
 *         &lt;element name="Audio" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}AudioTechnicalMetadataType"/&gt;
 *         &lt;element name="Video" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}VideoTechnicalMetadataType"/&gt;
 *         &lt;element ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}OtherCoreTechnicalMetadataAbstract"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoreMetadataType", propOrder = {
    "text",
    "document",
    "image",
    "audio",
    "video",
    "otherCoreTechnicalMetadataAbstract"
})
public class CoreMetadataType {

    @XmlElement(name = "Text")
    protected TextTechnicalMetadataType text;
    @XmlElement(name = "Document")
    protected DocumentTechnicalMetadataType document;
    @XmlElement(name = "Image")
    protected ImageTechnicalMetadataType image;
    @XmlElement(name = "Audio")
    protected AudioTechnicalMetadataType audio;
    @XmlElement(name = "Video")
    protected VideoTechnicalMetadataType video;
    @XmlElement(name = "OtherCoreTechnicalMetadataAbstract")
    protected OpenType otherCoreTechnicalMetadataAbstract;

    /**
     * Gets the value of the text property.
     *
     * @return
     *     possible object is
     *     {@link TextTechnicalMetadataType }
     *
     */
    public TextTechnicalMetadataType getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value
     *     allowed object is
     *     {@link TextTechnicalMetadataType }
     *
     */
    public void setText(TextTechnicalMetadataType value) {
        this.text = value;
    }

    /**
     * Gets the value of the document property.
     *
     * @return
     *     possible object is
     *     {@link DocumentTechnicalMetadataType }
     *
     */
    public DocumentTechnicalMetadataType getDocument() {
        return document;
    }

    /**
     * Sets the value of the document property.
     *
     * @param value
     *     allowed object is
     *     {@link DocumentTechnicalMetadataType }
     *
     */
    public void setDocument(DocumentTechnicalMetadataType value) {
        this.document = value;
    }

    /**
     * Gets the value of the image property.
     *
     * @return
     *     possible object is
     *     {@link ImageTechnicalMetadataType }
     *
     */
    public ImageTechnicalMetadataType getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     *
     * @param value
     *     allowed object is
     *     {@link ImageTechnicalMetadataType }
     *
     */
    public void setImage(ImageTechnicalMetadataType value) {
        this.image = value;
    }

    /**
     * Gets the value of the audio property.
     *
     * @return
     *     possible object is
     *     {@link AudioTechnicalMetadataType }
     *
     */
    public AudioTechnicalMetadataType getAudio() {
        return audio;
    }

    /**
     * Sets the value of the audio property.
     *
     * @param value
     *     allowed object is
     *     {@link AudioTechnicalMetadataType }
     *
     */
    public void setAudio(AudioTechnicalMetadataType value) {
        this.audio = value;
    }

    /**
     * Gets the value of the video property.
     *
     * @return
     *     possible object is
     *     {@link VideoTechnicalMetadataType }
     *
     */
    public VideoTechnicalMetadataType getVideo() {
        return video;
    }

    /**
     * Sets the value of the video property.
     *
     * @param value
     *     allowed object is
     *     {@link VideoTechnicalMetadataType }
     *
     */
    public void setVideo(VideoTechnicalMetadataType value) {
        this.video = value;
    }

    /**
     * Métadonnées pour un objet-données d’un autre type (base de données, 3D, programmes, formats propriétaires, etc.).
     *
     * @return
     *     possible object is
     *     {@link OpenType }
     *
     */
    public OpenType getOtherCoreTechnicalMetadataAbstract() {
        return otherCoreTechnicalMetadataAbstract;
    }

    /**
     * Sets the value of the otherCoreTechnicalMetadataAbstract property.
     *
     * @param value
     *     allowed object is
     *     {@link OpenType }
     *
     */
    public void setOtherCoreTechnicalMetadataAbstract(OpenType value) {
        this.otherCoreTechnicalMetadataAbstract = value;
    }

}
