/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DataObjectPackageType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataObjectPackageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="DataObjectGroup" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectGroupType"/&gt;
 *           &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *             &lt;element name="BinaryDataObject" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}BinaryDataObjectType"/&gt;
 *             &lt;element name="PhysicalDataObject" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}PhysicalDataObjectType"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="DescriptiveMetadata" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DescriptiveMetadataType"/&gt;
 *         &lt;element name="ManagementMetadata" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ManagementMetadataType"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}id"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataObjectPackageType", propOrder = {
    "dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject",
    "descriptiveMetadata",
    "managementMetadata"
})
public class DataObjectPackageType {

    @XmlElements({
        @XmlElement(name = "DataObjectGroup", type = DataObjectGroupType.class),
        @XmlElement(name = "BinaryDataObject", type = BinaryDataObjectType.class),
        @XmlElement(name = "PhysicalDataObject", type = PhysicalDataObjectType.class)
    })
    protected List<Object> dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject;
    @XmlElement(name = "DescriptiveMetadata", required = true)
    protected DescriptiveMetadataType descriptiveMetadata;
    @XmlElement(name = "ManagementMetadata", required = true)
    protected ManagementMetadataType managementMetadata;
    @XmlAttribute(name = "id", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    /**
     * Gets the value of the dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataObjectGroupOrBinaryDataObjectOrPhysicalDataObject().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataObjectGroupType }
     * {@link BinaryDataObjectType }
     * {@link PhysicalDataObjectType }
     *
     *
     */
    public List<Object> getDataObjectGroupOrBinaryDataObjectOrPhysicalDataObject() {
        if (dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject == null) {
            dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject = new ArrayList<Object>();
        }
        return this.dataObjectGroupOrBinaryDataObjectOrPhysicalDataObject;
    }

    /**
     * Gets the value of the descriptiveMetadata property.
     *
     * @return
     *     possible object is
     *     {@link DescriptiveMetadataType }
     *
     */
    public DescriptiveMetadataType getDescriptiveMetadata() {
        return descriptiveMetadata;
    }

    /**
     * Sets the value of the descriptiveMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link DescriptiveMetadataType }
     *
     */
    public void setDescriptiveMetadata(DescriptiveMetadataType value) {
        this.descriptiveMetadata = value;
    }

    /**
     * Gets the value of the managementMetadata property.
     *
     * @return
     *     possible object is
     *     {@link ManagementMetadataType }
     *
     */
    public ManagementMetadataType getManagementMetadata() {
        return managementMetadata;
    }

    /**
     * Sets the value of the managementMetadata property.
     *
     * @param value
     *     allowed object is
     *     {@link ManagementMetadataType }
     *
     */
    public void setManagementMetadata(ManagementMetadataType value) {
        this.managementMetadata = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setId(String value) {
        this.id = value;
    }

}
