/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for DataObjectOrArchiveUnitReferenceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DataObjectOrArchiveUnitReferenceType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="ArchiveUnitRefId" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ArchiveUnitRefIdType"/&gt;
 *         &lt;element name="DataObjectReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefType"/&gt;
 *         &lt;element name="RepositoryArchiveUnitPID" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType"/&gt;
 *         &lt;element name="RepositoryObjectPID" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType"/&gt;
 *         &lt;element name="ExternalReference" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataObjectOrArchiveUnitReferenceType", propOrder = {
    "archiveUnitRefId",
    "dataObjectReference",
    "repositoryArchiveUnitPID",
    "repositoryObjectPID",
    "externalReference"
})
public class DataObjectOrArchiveUnitReferenceType {

    @XmlElement(name = "ArchiveUnitRefId")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object archiveUnitRefId;
    @XmlElement(name = "DataObjectReference")
    protected DataObjectRefType dataObjectReference;
    @XmlElement(name = "RepositoryArchiveUnitPID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String repositoryArchiveUnitPID;
    @XmlElement(name = "RepositoryObjectPID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String repositoryObjectPID;
    @XmlElement(name = "ExternalReference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String externalReference;

    /**
     * Gets the value of the archiveUnitRefId property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getArchiveUnitRefId() {
        return archiveUnitRefId;
    }

    /**
     * Sets the value of the archiveUnitRefId property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setArchiveUnitRefId(Object value) {
        this.archiveUnitRefId = value;
    }

    /**
     * Gets the value of the dataObjectReference property.
     *
     * @return
     *     possible object is
     *     {@link DataObjectRefType }
     *
     */
    public DataObjectRefType getDataObjectReference() {
        return dataObjectReference;
    }

    /**
     * Sets the value of the dataObjectReference property.
     *
     * @param value
     *     allowed object is
     *     {@link DataObjectRefType }
     *
     */
    public void setDataObjectReference(DataObjectRefType value) {
        this.dataObjectReference = value;
    }

    /**
     * Gets the value of the repositoryArchiveUnitPID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRepositoryArchiveUnitPID() {
        return repositoryArchiveUnitPID;
    }

    /**
     * Sets the value of the repositoryArchiveUnitPID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRepositoryArchiveUnitPID(String value) {
        this.repositoryArchiveUnitPID = value;
    }

    /**
     * Gets the value of the repositoryObjectPID property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRepositoryObjectPID() {
        return repositoryObjectPID;
    }

    /**
     * Sets the value of the repositoryObjectPID property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRepositoryObjectPID(String value) {
        this.repositoryObjectPID = value;
    }

    /**
     * Gets the value of the externalReference property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExternalReference() {
        return externalReference;
    }

    /**
     * Sets the value of the externalReference property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExternalReference(String value) {
        this.externalReference = value;
    }

}
