/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Permet de définir les métadonnées de description. Peut être étendu.
 *
 * <p>Java class for DescriptiveMetadataContentType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DescriptiveMetadataContentType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ObjectGroup"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptiveMetadataContentType", propOrder = {
    "descriptionLevel",
    "title",
    "filePlanPosition",
    "systemId",
    "originatingSystemId",
    "archivalAgencyArchiveUnitIdentifier",
    "originatingAgencyArchiveUnitIdentifier",
    "transferringAgencyArchiveUnitIdentifier",
    "description",
    "custodialHistory",
    "type",
    "documentType",
    "language",
    "descriptionLanguage",
    "status",
    "version",
    "tag",
    "keyword",
    "coverage",
    "originatingAgency",
    "submissionAgency",
    "agentAbstract",
    "authorizedAgent",
    "writer",
    "addressee",
    "recipient",
    "transmitter",
    "sender",
    "source",
    "relatedObjectReference",
    "createdDate",
    "transactedDate",
    "acquiredDate",
    "sentDate",
    "receivedDate",
    "registeredDate",
    "startDate",
    "endDate",
    "event",
    "signature",
    "gps",
    "objectGroupExtenstionAbstract"
})
public class DescriptiveMetadataContentType {

    @XmlElement(name = "DescriptionLevel")
    @XmlSchemaType(name = "token")
    protected LevelType descriptionLevel;
    @XmlElement(name = "Title")
    protected List<TextType> title;
    @XmlElement(name = "FilePlanPosition")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> filePlanPosition;
    @XmlElement(name = "SystemId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> systemId;
    @XmlElement(name = "OriginatingSystemId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> originatingSystemId;
    @XmlElement(name = "ArchivalAgencyArchiveUnitIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> archivalAgencyArchiveUnitIdentifier;
    @XmlElement(name = "OriginatingAgencyArchiveUnitIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> originatingAgencyArchiveUnitIdentifier;
    @XmlElement(name = "TransferringAgencyArchiveUnitIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> transferringAgencyArchiveUnitIdentifier;
    @XmlElement(name = "Description")
    protected List<TextType> description;
    @XmlElement(name = "CustodialHistory")
    protected DescriptiveMetadataContentType.CustodialHistory custodialHistory;
    @XmlElement(name = "Type")
    protected TextType type;
    @XmlElement(name = "DocumentType")
    protected TextType documentType;
    @XmlElement(name = "Language")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected List<String> language;
    @XmlElement(name = "DescriptionLanguage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String descriptionLanguage;
    @XmlElement(name = "Status")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String status;
    @XmlElement(name = "Version")
    protected String version;
    @XmlElement(name = "Tag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> tag;
    @XmlElement(name = "Keyword")
    protected List<KeywordsType> keyword;
    @XmlElement(name = "Coverage")
    protected CoverageType coverage;
    @XmlElement(name = "OriginatingAgency")
    protected OrganizationType originatingAgency;
    @XmlElement(name = "SubmissionAgency")
    protected OrganizationType submissionAgency;
    @XmlElement(name = "AgentAbstract")
    protected List<AgentType> agentAbstract;
    @XmlElement(name = "AuthorizedAgent")
    protected List<AgentType> authorizedAgent;
    @XmlElement(name = "Writer")
    protected List<DescriptiveMetadataContentType.Writer> writer;
    @XmlElement(name = "Addressee")
    protected List<AgentType> addressee;
    @XmlElement(name = "Recipient")
    protected List<AgentType> recipient;
    @XmlElement(name = "Transmitter")
    protected List<AgentType> transmitter;
    @XmlElement(name = "Sender")
    protected List<AgentType> sender;
    @XmlElement(name = "Source")
    protected String source;
    @XmlElement(name = "RelatedObjectReference")
    protected DescriptiveMetadataContentType.RelatedObjectReference relatedObjectReference;
    @XmlElement(name = "CreatedDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String createdDate;
    @XmlElement(name = "TransactedDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String transactedDate;
    @XmlElement(name = "AcquiredDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String acquiredDate;
    @XmlElement(name = "SentDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String sentDate;
    @XmlElement(name = "ReceivedDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String receivedDate;
    @XmlElement(name = "RegisteredDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String registeredDate;
    @XmlElement(name = "StartDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String startDate;
    @XmlElement(name = "EndDate")
    @XmlSchemaType(name = "anySimpleType")
    protected String endDate;
    @XmlElement(name = "Event")
    protected List<EventType> event;
    @XmlElement(name = "Signature")
    protected List<DescriptiveMetadataContentType.Signature> signature;
    @XmlElement(name = "Gps")
    protected GpsType gps;
    @XmlElement(name = "ObjectGroupExtenstionAbstract")
    protected List<Object> objectGroupExtenstionAbstract;

    /**
     * Gets the value of the descriptionLevel property.
     *
     * @return
     *     possible object is
     *     {@link LevelType }
     *
     */
    public LevelType getDescriptionLevel() {
        return descriptionLevel;
    }

    /**
     * Sets the value of the descriptionLevel property.
     *
     * @param value
     *     allowed object is
     *     {@link LevelType }
     *
     */
    public void setDescriptionLevel(LevelType value) {
        this.descriptionLevel = value;
    }

    /**
     * Gets the value of the title property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     *
     *
     */
    public List<TextType> getTitle() {
        if (title == null) {
            title = new ArrayList<TextType>();
        }
        return this.title;
    }

    /**
     * Gets the value of the filePlanPosition property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filePlanPosition property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilePlanPosition().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getFilePlanPosition() {
        if (filePlanPosition == null) {
            filePlanPosition = new ArrayList<String>();
        }
        return this.filePlanPosition;
    }

    /**
     * Gets the value of the systemId property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemId property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemId().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getSystemId() {
        if (systemId == null) {
            systemId = new ArrayList<String>();
        }
        return this.systemId;
    }

    /**
     * Gets the value of the originatingSystemId property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originatingSystemId property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginatingSystemId().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getOriginatingSystemId() {
        if (originatingSystemId == null) {
            originatingSystemId = new ArrayList<String>();
        }
        return this.originatingSystemId;
    }

    /**
     * Gets the value of the archivalAgencyArchiveUnitIdentifier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the archivalAgencyArchiveUnitIdentifier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArchivalAgencyArchiveUnitIdentifier().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getArchivalAgencyArchiveUnitIdentifier() {
        if (archivalAgencyArchiveUnitIdentifier == null) {
            archivalAgencyArchiveUnitIdentifier = new ArrayList<String>();
        }
        return this.archivalAgencyArchiveUnitIdentifier;
    }

    /**
     * Gets the value of the originatingAgencyArchiveUnitIdentifier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the originatingAgencyArchiveUnitIdentifier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOriginatingAgencyArchiveUnitIdentifier().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getOriginatingAgencyArchiveUnitIdentifier() {
        if (originatingAgencyArchiveUnitIdentifier == null) {
            originatingAgencyArchiveUnitIdentifier = new ArrayList<String>();
        }
        return this.originatingAgencyArchiveUnitIdentifier;
    }

    /**
     * Gets the value of the transferringAgencyArchiveUnitIdentifier property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transferringAgencyArchiveUnitIdentifier property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransferringAgencyArchiveUnitIdentifier().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getTransferringAgencyArchiveUnitIdentifier() {
        if (transferringAgencyArchiveUnitIdentifier == null) {
            transferringAgencyArchiveUnitIdentifier = new ArrayList<String>();
        }
        return this.transferringAgencyArchiveUnitIdentifier;
    }

    /**
     * Gets the value of the description property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     *
     *
     */
    public List<TextType> getDescription() {
        if (description == null) {
            description = new ArrayList<TextType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the custodialHistory property.
     *
     * @return
     *     possible object is
     *     {@link DescriptiveMetadataContentType.CustodialHistory }
     *
     */
    public DescriptiveMetadataContentType.CustodialHistory getCustodialHistory() {
        return custodialHistory;
    }

    /**
     * Sets the value of the custodialHistory property.
     *
     * @param value
     *     allowed object is
     *     {@link DescriptiveMetadataContentType.CustodialHistory }
     *
     */
    public void setCustodialHistory(DescriptiveMetadataContentType.CustodialHistory value) {
        this.custodialHistory = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link TextType }
     *
     */
    public TextType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link TextType }
     *
     */
    public void setType(TextType value) {
        this.type = value;
    }

    /**
     * Gets the value of the documentType property.
     *
     * @return
     *     possible object is
     *     {@link TextType }
     *
     */
    public TextType getDocumentType() {
        return documentType;
    }

    /**
     * Sets the value of the documentType property.
     *
     * @param value
     *     allowed object is
     *     {@link TextType }
     *
     */
    public void setDocumentType(TextType value) {
        this.documentType = value;
    }

    /**
     * Gets the value of the language property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the descriptionLanguage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDescriptionLanguage() {
        return descriptionLanguage;
    }

    /**
     * Sets the value of the descriptionLanguage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDescriptionLanguage(String value) {
        this.descriptionLanguage = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the version property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the tag property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tag property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTag().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     *
     *
     */
    public List<String> getTag() {
        if (tag == null) {
            tag = new ArrayList<String>();
        }
        return this.tag;
    }

    /**
     * Gets the value of the keyword property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyword property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyword().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeywordsType }
     *
     *
     */
    public List<KeywordsType> getKeyword() {
        if (keyword == null) {
            keyword = new ArrayList<KeywordsType>();
        }
        return this.keyword;
    }

    /**
     * Gets the value of the coverage property.
     *
     * @return
     *     possible object is
     *     {@link CoverageType }
     *
     */
    public CoverageType getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     *
     * @param value
     *     allowed object is
     *     {@link CoverageType }
     *
     */
    public void setCoverage(CoverageType value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the originatingAgency property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *
     */
    public OrganizationType getOriginatingAgency() {
        return originatingAgency;
    }

    /**
     * Sets the value of the originatingAgency property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *
     */
    public void setOriginatingAgency(OrganizationType value) {
        this.originatingAgency = value;
    }

    /**
     * Gets the value of the submissionAgency property.
     *
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *
     */
    public OrganizationType getSubmissionAgency() {
        return submissionAgency;
    }

    /**
     * Sets the value of the submissionAgency property.
     *
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *
     */
    public void setSubmissionAgency(OrganizationType value) {
        this.submissionAgency = value;
    }

    /**
     * Gets the value of the agentAbstract property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentAbstract property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentAbstract().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentType }
     *
     *
     */
    public List<AgentType> getAgentAbstract() {
        if (agentAbstract == null) {
            agentAbstract = new ArrayList<AgentType>();
        }
        return this.agentAbstract;
    }

    /**
     * Gets the value of the authorizedAgent property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the authorizedAgent property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAuthorizedAgent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentType }
     *
     *
     */
    public List<AgentType> getAuthorizedAgent() {
        if (authorizedAgent == null) {
            authorizedAgent = new ArrayList<AgentType>();
        }
        return this.authorizedAgent;
    }

    /**
     * Gets the value of the writer property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the writer property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWriter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptiveMetadataContentType.Writer }
     *
     *
     */
    public List<DescriptiveMetadataContentType.Writer> getWriter() {
        if (writer == null) {
            writer = new ArrayList<DescriptiveMetadataContentType.Writer>();
        }
        return this.writer;
    }

    /**
     * Gets the value of the addressee property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressee property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressee().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentType }
     *
     *
     */
    public List<AgentType> getAddressee() {
        if (addressee == null) {
            addressee = new ArrayList<AgentType>();
        }
        return this.addressee;
    }

    /**
     * Gets the value of the recipient property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recipient property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecipient().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentType }
     *
     *
     */
    public List<AgentType> getRecipient() {
        if (recipient == null) {
            recipient = new ArrayList<AgentType>();
        }
        return this.recipient;
    }

    /**
     * Gets the value of the transmitter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transmitter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransmitter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentType }
     *
     *
     */
    public List<AgentType> getTransmitter() {
        if (transmitter == null) {
            transmitter = new ArrayList<AgentType>();
        }
        return this.transmitter;
    }

    /**
     * Gets the value of the sender property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sender property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSender().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AgentType }
     *
     *
     */
    public List<AgentType> getSender() {
        if (sender == null) {
            sender = new ArrayList<AgentType>();
        }
        return this.sender;
    }

    /**
     * Gets the value of the source property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the relatedObjectReference property.
     *
     * @return
     *     possible object is
     *     {@link DescriptiveMetadataContentType.RelatedObjectReference }
     *
     */
    public DescriptiveMetadataContentType.RelatedObjectReference getRelatedObjectReference() {
        return relatedObjectReference;
    }

    /**
     * Sets the value of the relatedObjectReference property.
     *
     * @param value
     *     allowed object is
     *     {@link DescriptiveMetadataContentType.RelatedObjectReference }
     *
     */
    public void setRelatedObjectReference(DescriptiveMetadataContentType.RelatedObjectReference value) {
        this.relatedObjectReference = value;
    }

    /**
     * Gets the value of the createdDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreatedDate() {
        return createdDate;
    }

    /**
     * Sets the value of the createdDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreatedDate(String value) {
        this.createdDate = value;
    }

    /**
     * Gets the value of the transactedDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTransactedDate() {
        return transactedDate;
    }

    /**
     * Sets the value of the transactedDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTransactedDate(String value) {
        this.transactedDate = value;
    }

    /**
     * Gets the value of the acquiredDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAcquiredDate() {
        return acquiredDate;
    }

    /**
     * Sets the value of the acquiredDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAcquiredDate(String value) {
        this.acquiredDate = value;
    }

    /**
     * Gets the value of the sentDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSentDate() {
        return sentDate;
    }

    /**
     * Sets the value of the sentDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSentDate(String value) {
        this.sentDate = value;
    }

    /**
     * Gets the value of the receivedDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getReceivedDate() {
        return receivedDate;
    }

    /**
     * Sets the value of the receivedDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setReceivedDate(String value) {
        this.receivedDate = value;
    }

    /**
     * Gets the value of the registeredDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRegisteredDate() {
        return registeredDate;
    }

    /**
     * Sets the value of the registeredDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRegisteredDate(String value) {
        this.registeredDate = value;
    }

    /**
     * Gets the value of the startDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStartDate(String value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEndDate(String value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the event property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the event property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvent().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventType }
     *
     *
     */
    public List<EventType> getEvent() {
        if (event == null) {
            event = new ArrayList<EventType>();
        }
        return this.event;
    }

    /**
     * Gets the value of the signature property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signature property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignature().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptiveMetadataContentType.Signature }
     *
     *
     */
    public List<DescriptiveMetadataContentType.Signature> getSignature() {
        if (signature == null) {
            signature = new ArrayList<DescriptiveMetadataContentType.Signature>();
        }
        return this.signature;
    }

    /**
     * Gets the value of the gps property.
     *
     * @return
     *     possible object is
     *     {@link GpsType }
     *
     */
    public GpsType getGps() {
        return gps;
    }

    /**
     * Sets the value of the gps property.
     *
     * @param value
     *     allowed object is
     *     {@link GpsType }
     *
     */
    public void setGps(GpsType value) {
        this.gps = value;
    }

    /**
     * Gets the value of the objectGroupExtenstionAbstract property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectGroupExtenstionAbstract property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectGroupExtenstionAbstract().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     *
     *
     */
    public List<Object> getObjectGroupExtenstionAbstract() {
        if (objectGroupExtenstionAbstract == null) {
            objectGroupExtenstionAbstract = new ArrayList<Object>();
        }
        return this.objectGroupExtenstionAbstract;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CustodialHistoryItem" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;simpleContent&gt;
     *               &lt;extension base="&lt;fr:gouv:culture:archivesdefrance:seda:v2.1&gt;TextType"&gt;
     *                 &lt;attribute name="when" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DateType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/simpleContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="CustodialHistoryFile" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectRefType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "custodialHistoryItem",
        "custodialHistoryFile"
    })
    public static class CustodialHistory {

        @XmlElement(name = "CustodialHistoryItem", required = true)
        protected List<DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem> custodialHistoryItem;
        @XmlElement(name = "CustodialHistoryFile")
        protected DataObjectRefType custodialHistoryFile;

        /**
         * Gets the value of the custodialHistoryItem property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the custodialHistoryItem property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustodialHistoryItem().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem }
         *
         *
         */
        public List<DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem> getCustodialHistoryItem() {
            if (custodialHistoryItem == null) {
                custodialHistoryItem = new ArrayList<DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem>();
            }
            return this.custodialHistoryItem;
        }

        /**
         * Gets the value of the custodialHistoryFile property.
         *
         * @return
         *     possible object is
         *     {@link DataObjectRefType }
         *
         */
        public DataObjectRefType getCustodialHistoryFile() {
            return custodialHistoryFile;
        }

        /**
         * Sets the value of the custodialHistoryFile property.
         *
         * @param value
         *     allowed object is
         *     {@link DataObjectRefType }
         *
         */
        public void setCustodialHistoryFile(DataObjectRefType value) {
            this.custodialHistoryFile = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;simpleContent&gt;
         *     &lt;extension base="&lt;fr:gouv:culture:archivesdefrance:seda:v2.1&gt;TextType"&gt;
         *       &lt;attribute name="when" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DateType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/simpleContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CustodialHistoryItem
            extends TextType
        {

            @XmlAttribute(name = "when")
            protected String when;

            /**
             * Gets the value of the when property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getWhen() {
                return when;
            }

            /**
             * Sets the value of the when property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setWhen(String value) {
                this.when = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="IsVersionOf" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Replaces" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="Requires" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="IsPartOf" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="References" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DataObjectOrArchiveUnitReferenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isVersionOf",
        "replaces",
        "requires",
        "isPartOf",
        "references"
    })
    public static class RelatedObjectReference {

        @XmlElement(name = "IsVersionOf")
        protected List<DataObjectOrArchiveUnitReferenceType> isVersionOf;
        @XmlElement(name = "Replaces")
        protected List<DataObjectOrArchiveUnitReferenceType> replaces;
        @XmlElement(name = "Requires")
        protected List<DataObjectOrArchiveUnitReferenceType> requires;
        @XmlElement(name = "IsPartOf")
        protected List<DataObjectOrArchiveUnitReferenceType> isPartOf;
        @XmlElement(name = "References")
        protected List<DataObjectOrArchiveUnitReferenceType> references;

        /**
         * Gets the value of the isVersionOf property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the isVersionOf property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIsVersionOf().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataObjectOrArchiveUnitReferenceType }
         *
         *
         */
        public List<DataObjectOrArchiveUnitReferenceType> getIsVersionOf() {
            if (isVersionOf == null) {
                isVersionOf = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
            }
            return this.isVersionOf;
        }

        /**
         * Gets the value of the replaces property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the replaces property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReplaces().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataObjectOrArchiveUnitReferenceType }
         *
         *
         */
        public List<DataObjectOrArchiveUnitReferenceType> getReplaces() {
            if (replaces == null) {
                replaces = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
            }
            return this.replaces;
        }

        /**
         * Gets the value of the requires property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the requires property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRequires().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataObjectOrArchiveUnitReferenceType }
         *
         *
         */
        public List<DataObjectOrArchiveUnitReferenceType> getRequires() {
            if (requires == null) {
                requires = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
            }
            return this.requires;
        }

        /**
         * Gets the value of the isPartOf property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the isPartOf property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIsPartOf().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataObjectOrArchiveUnitReferenceType }
         *
         *
         */
        public List<DataObjectOrArchiveUnitReferenceType> getIsPartOf() {
            if (isPartOf == null) {
                isPartOf = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
            }
            return this.isPartOf;
        }

        /**
         * Gets the value of the references property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the references property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReferences().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DataObjectOrArchiveUnitReferenceType }
         *
         *
         */
        public List<DataObjectOrArchiveUnitReferenceType> getReferences() {
            if (references == null) {
                references = new ArrayList<DataObjectOrArchiveUnitReferenceType>();
            }
            return this.references;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Signer" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}SignerGroup"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Validator"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ValidatorGroup"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Masterdata" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}CodeType" minOccurs="0"/&gt;
     *         &lt;element name="ReferencedObject" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}ReferencedObjectType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "signer",
        "validator",
        "masterdata",
        "referencedObject"
    })
    public static class Signature {

        @XmlElement(name = "Signer", required = true)
        protected List<DescriptiveMetadataContentType.Signature.Signer> signer;
        @XmlElement(name = "Validator", required = true)
        protected DescriptiveMetadataContentType.Signature.Validator validator;
        @XmlElement(name = "Masterdata")
        protected CodeType masterdata;
        @XmlElement(name = "ReferencedObject", required = true)
        protected ReferencedObjectType referencedObject;

        /**
         * Gets the value of the signer property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the signer property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSigner().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DescriptiveMetadataContentType.Signature.Signer }
         *
         *
         */
        public List<DescriptiveMetadataContentType.Signature.Signer> getSigner() {
            if (signer == null) {
                signer = new ArrayList<DescriptiveMetadataContentType.Signature.Signer>();
            }
            return this.signer;
        }

        /**
         * Gets the value of the validator property.
         *
         * @return
         *     possible object is
         *     {@link DescriptiveMetadataContentType.Signature.Validator }
         *
         */
        public DescriptiveMetadataContentType.Signature.Validator getValidator() {
            return validator;
        }

        /**
         * Sets the value of the validator property.
         *
         * @param value
         *     allowed object is
         *     {@link DescriptiveMetadataContentType.Signature.Validator }
         *
         */
        public void setValidator(DescriptiveMetadataContentType.Signature.Validator value) {
            this.validator = value;
        }

        /**
         * Gets the value of the masterdata property.
         *
         * @return
         *     possible object is
         *     {@link CodeType }
         *
         */
        public CodeType getMasterdata() {
            return masterdata;
        }

        /**
         * Sets the value of the masterdata property.
         *
         * @param value
         *     allowed object is
         *     {@link CodeType }
         *
         */
        public void setMasterdata(CodeType value) {
            this.masterdata = value;
        }

        /**
         * Gets the value of the referencedObject property.
         *
         * @return
         *     possible object is
         *     {@link ReferencedObjectType }
         *
         */
        public ReferencedObjectType getReferencedObject() {
            return referencedObject;
        }

        /**
         * Sets the value of the referencedObject property.
         *
         * @param value
         *     allowed object is
         *     {@link ReferencedObjectType }
         *
         */
        public void setReferencedObject(ReferencedObjectType value) {
            this.referencedObject = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}SignerGroup"/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Signer {

            @XmlElementRefs({
                @XmlElementRef(name = "GivenName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "FirstName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DeathPlace", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BirthDate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "FullName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BirthPlace", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Gender", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Mandate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DeathDate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Function", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Nationality", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Identifier", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "SigningTime", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BirthName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Role", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Corpname", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Position", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Activity", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> content;

            /**
             * Gets the rest of the content model.
             *
             * <p>
             * You are getting this "catch-all" property because of the following reason:
             * The field name "Identifier" is used by two different parts of a schema. See:
             * line 884 of seda/seda-2.1-ontology.xsd
             * line 872 of seda/seda-2.1-ontology.xsd
             * <p>
             * To get rid of this property, apply a property customization to one
             * of both of the following declarations to change their names:
             * Gets the value of the content property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             *
             *
             */
            public List<JAXBElement<?>> getContent() {
                if (content == null) {
                    content = new ArrayList<JAXBElement<?>>();
                }
                return this.content;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}ValidatorGroup"/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class Validator {

            @XmlElementRefs({
                @XmlElementRef(name = "Role", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Position", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BirthPlace", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DeathDate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Nationality", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Mandate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "ValidationTime", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "DeathPlace", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "FullName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BirthName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Gender", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "FirstName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Function", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Identifier", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "GivenName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Corpname", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "Activity", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "BirthDate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> content;

            /**
             * Gets the rest of the content model.
             *
             * <p>
             * You are getting this "catch-all" property because of the following reason:
             * The field name "Identifier" is used by two different parts of a schema. See:
             * line 884 of seda/seda-2.1-ontology.xsd
             * line 872 of seda/seda-2.1-ontology.xsd
             * <p>
             * To get rid of this property, apply a property customization to one
             * of both of the following declarations to change their names:
             * Gets the value of the content property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link TextType }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             *
             *
             */
            public List<JAXBElement<?>> getContent() {
                if (content == null) {
                    content = new ArrayList<JAXBElement<?>>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}LocationGroup"/&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "geogname",
                "address",
                "postalCode",
                "city",
                "region",
                "country"
            })
            public static class BirthPlace {

                @XmlElement(name = "Geogname")
                protected String geogname;
                @XmlElement(name = "Address")
                protected String address;
                @XmlElement(name = "PostalCode")
                protected String postalCode;
                @XmlElement(name = "City")
                protected String city;
                @XmlElement(name = "Region")
                protected String region;
                @XmlElement(name = "Country")
                protected String country;

                /**
                 * Gets the value of the geogname property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getGeogname() {
                    return geogname;
                }

                /**
                 * Sets the value of the geogname property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setGeogname(String value) {
                    this.geogname = value;
                }

                /**
                 * Gets the value of the address property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getAddress() {
                    return address;
                }

                /**
                 * Sets the value of the address property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setAddress(String value) {
                    this.address = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setPostalCode(String value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the city property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the region property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRegion() {
                    return region;
                }

                /**
                 * Sets the value of the region property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRegion(String value) {
                    this.region = value;
                }

                /**
                 * Gets the value of the country property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}LocationGroup"/&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "geogname",
                "address",
                "postalCode",
                "city",
                "region",
                "country"
            })
            public static class DeathPlace {

                @XmlElement(name = "Geogname")
                protected String geogname;
                @XmlElement(name = "Address")
                protected String address;
                @XmlElement(name = "PostalCode")
                protected String postalCode;
                @XmlElement(name = "City")
                protected String city;
                @XmlElement(name = "Region")
                protected String region;
                @XmlElement(name = "Country")
                protected String country;

                /**
                 * Gets the value of the geogname property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getGeogname() {
                    return geogname;
                }

                /**
                 * Sets the value of the geogname property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setGeogname(String value) {
                    this.geogname = value;
                }

                /**
                 * Gets the value of the address property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getAddress() {
                    return address;
                }

                /**
                 * Sets the value of the address property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setAddress(String value) {
                    this.address = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setPostalCode(String value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the city property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the region property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getRegion() {
                    return region;
                }

                /**
                 * Sets the value of the region property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setRegion(String value) {
                    this.region = value;
                }

                /**
                 * Gets the value of the country property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;group ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}WriterGroup"/&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Writer {

        @XmlElementRefs({
            @XmlElementRef(name = "Function", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Activity", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "BirthName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Corpname", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Role", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "FirstName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Mandate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Gender", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "BirthDate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "BirthPlace", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "GivenName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "FullName", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Position", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "DeathDate", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "DeathPlace", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Nationality", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "Identifier", namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> content;

        /**
         * Gets the rest of the content model.
         *
         * <p>
         * You are getting this "catch-all" property because of the following reason:
         * The field name "Identifier" is used by two different parts of a schema. See:
         * line 884 of seda/seda-2.1-ontology.xsd
         * line 872 of seda/seda-2.1-ontology.xsd
         * <p>
         * To get rid of this property, apply a property customization to one
         * of both of the following declarations to change their names:
         * Gets the value of the content property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link TextType }{@code >}
         * {@link JAXBElement }{@code <}{@link TextType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link TextType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link TextType }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link TextType }{@code >}
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         *
         *
         */
        public List<JAXBElement<?>> getContent() {
            if (content == null) {
                content = new ArrayList<JAXBElement<?>>();
            }
            return this.content;
        }

    }

}
