/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for EventType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="EventType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EventIdentifier" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element name="EventTypeCode" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element name="EventType" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element name="EventDateTime" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}DateType"/&gt;
 *         &lt;element name="EventDetail" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}TextType" minOccurs="0"/&gt;
 *         &lt;element name="Outcome" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element name="OutcomeDetail" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element name="OutcomeDetailMessage" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element name="EventDetailData" type="{fr:gouv:culture:archivesdefrance:seda:v2.1}NonEmptyTokenType" minOccurs="0"/&gt;
 *         &lt;element ref="{fr:gouv:culture:archivesdefrance:seda:v2.1}EventAbstract" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventType", propOrder = {
    "eventIdentifier",
    "eventTypeCode",
    "eventType",
    "eventDateTime",
    "eventDetail",
    "outcome",
    "outcomeDetail",
    "outcomeDetailMessage",
    "eventDetailData",
    "eventAbstract"
})
@XmlSeeAlso({
    fr.gouv.vitamui.commons.vitam.seda.DataObjectGroupType.LogBook.Event.class,
    fr.gouv.vitamui.commons.vitam.seda.ManagementMetadataType.LogBook.Event.class
})
public class EventType {

    @XmlElement(name = "EventIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String eventIdentifier;
    @XmlElement(name = "EventTypeCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String eventTypeCode;
    @XmlElement(name = "EventType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String eventType;
    @XmlElement(name = "EventDateTime", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String eventDateTime;
    @XmlElement(name = "EventDetail")
    protected TextType eventDetail;
    @XmlElement(name = "Outcome")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String outcome;
    @XmlElement(name = "OutcomeDetail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String outcomeDetail;
    @XmlElement(name = "OutcomeDetailMessage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String outcomeDetailMessage;
    @XmlElement(name = "EventDetailData")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String eventDetailData;
    @XmlElement(name = "EventAbstract")
    protected List<Object> eventAbstract;

    /**
     * Gets the value of the eventIdentifier property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventIdentifier() {
        return eventIdentifier;
    }

    /**
     * Sets the value of the eventIdentifier property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventIdentifier(String value) {
        this.eventIdentifier = value;
    }

    /**
     * Gets the value of the eventTypeCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventTypeCode() {
        return eventTypeCode;
    }

    /**
     * Sets the value of the eventTypeCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventTypeCode(String value) {
        this.eventTypeCode = value;
    }

    /**
     * Gets the value of the eventType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the value of the eventType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventType(String value) {
        this.eventType = value;
    }

    /**
     * Gets the value of the eventDateTime property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventDateTime() {
        return eventDateTime;
    }

    /**
     * Sets the value of the eventDateTime property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventDateTime(String value) {
        this.eventDateTime = value;
    }

    /**
     * Gets the value of the eventDetail property.
     *
     * @return
     *     possible object is
     *     {@link TextType }
     *
     */
    public TextType getEventDetail() {
        return eventDetail;
    }

    /**
     * Sets the value of the eventDetail property.
     *
     * @param value
     *     allowed object is
     *     {@link TextType }
     *
     */
    public void setEventDetail(TextType value) {
        this.eventDetail = value;
    }

    /**
     * Gets the value of the outcome property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOutcome() {
        return outcome;
    }

    /**
     * Sets the value of the outcome property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOutcome(String value) {
        this.outcome = value;
    }

    /**
     * Gets the value of the outcomeDetail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOutcomeDetail() {
        return outcomeDetail;
    }

    /**
     * Sets the value of the outcomeDetail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOutcomeDetail(String value) {
        this.outcomeDetail = value;
    }

    /**
     * Gets the value of the outcomeDetailMessage property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOutcomeDetailMessage() {
        return outcomeDetailMessage;
    }

    /**
     * Sets the value of the outcomeDetailMessage property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOutcomeDetailMessage(String value) {
        this.outcomeDetailMessage = value;
    }

    /**
     * Gets the value of the eventDetailData property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEventDetailData() {
        return eventDetailData;
    }

    /**
     * Sets the value of the eventDetailData property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEventDetailData(String value) {
        this.eventDetailData = value;
    }

    /**
     * Permet d'étendre de nouveaux types d'évenéments.Gets the value of the eventAbstract property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventAbstract property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventAbstract().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     *
     *
     */
    public List<Object> getEventAbstract() {
        if (eventAbstract == null) {
            eventAbstract = new ArrayList<Object>();
        }
        return this.eventAbstract;
    }

}
