/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Informations sur le fichier lui-même (d'un point de vue technique).
 *
 * <p>Java class for FileInfoType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FileInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Filename" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CreatingApplicationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreatingApplicationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DateCreatedByApplication" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CreatingOs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="CreatingOsVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileInfoType", propOrder = {
    "filename",
    "creatingApplicationName",
    "creatingApplicationVersion",
    "dateCreatedByApplication",
    "creatingOs",
    "creatingOsVersion",
    "lastModified"
})
public class FileInfoType {

    @XmlElement(name = "Filename", required = true)
    protected String filename;
    @XmlElement(name = "CreatingApplicationName")
    protected String creatingApplicationName;
    @XmlElement(name = "CreatingApplicationVersion")
    protected String creatingApplicationVersion;
    @XmlElement(name = "DateCreatedByApplication")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateCreatedByApplication;
    @XmlElement(name = "CreatingOs")
    protected String creatingOs;
    @XmlElement(name = "CreatingOsVersion")
    protected String creatingOsVersion;
    @XmlElement(name = "LastModified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;

    /**
     * Gets the value of the filename property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFilename(String value) {
        this.filename = value;
    }

    /**
     * Gets the value of the creatingApplicationName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreatingApplicationName() {
        return creatingApplicationName;
    }

    /**
     * Sets the value of the creatingApplicationName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreatingApplicationName(String value) {
        this.creatingApplicationName = value;
    }

    /**
     * Gets the value of the creatingApplicationVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreatingApplicationVersion() {
        return creatingApplicationVersion;
    }

    /**
     * Sets the value of the creatingApplicationVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreatingApplicationVersion(String value) {
        this.creatingApplicationVersion = value;
    }

    /**
     * Gets the value of the dateCreatedByApplication property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateCreatedByApplication() {
        return dateCreatedByApplication;
    }

    /**
     * Sets the value of the dateCreatedByApplication property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateCreatedByApplication(XMLGregorianCalendar value) {
        this.dateCreatedByApplication = value;
    }

    /**
     * Gets the value of the creatingOs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreatingOs() {
        return creatingOs;
    }

    /**
     * Sets the value of the creatingOs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreatingOs(String value) {
        this.creatingOs = value;
    }

    /**
     * Gets the value of the creatingOsVersion property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCreatingOsVersion() {
        return creatingOsVersion;
    }

    /**
     * Sets the value of the creatingOsVersion property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCreatingOsVersion(String value) {
        this.creatingOsVersion = value;
    }

    /**
     * Gets the value of the lastModified property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

}
