/**
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2020)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.02.12 at 11:35:36 AM CET
//


package fr.gouv.vitamui.commons.vitam.seda;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the fr.gouv.vitamui.commons.vitam.seda package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _ObjectGroupExtenstionAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ObjectGroupExtenstionAbstract");
    private static final QName _OtherDimensionsAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherDimensionsAbstract");
    private static final QName _OtherCoreTechnicalMetadataAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherCoreTechnicalMetadataAbstract");
    private static final QName _ArchiveUnitReferenceAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveUnitReferenceAbstract");
    private static final QName _OtherManagementAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherManagementAbstract");
    private static final QName _OtherCodeListAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "OtherCodeListAbstract");
    private static final QName _AgentAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AgentAbstract");
    private static final QName _EventAbstract_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "EventAbstract");
    private static final QName _Acknowledgement_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Acknowledgement");
    private static final QName _ArchiveDeliveryRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveDeliveryRequest");
    private static final QName _ArchiveRestitutionRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveRestitutionRequest");
    private static final QName _ArchiveTransfer_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransfer");
    private static final QName _ArchiveTransferRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransferRequest");
    private static final QName _AuthorizationControlAuthorityRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationControlAuthorityRequest");
    private static final QName _AuthorizationOriginatingAgencyRequest_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationOriginatingAgencyRequest");
    private static final QName _ArchiveDeliveryRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveDeliveryRequestReply");
    private static final QName _ArchiveRestitutionRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveRestitutionRequestReply");
    private static final QName _ArchiveTransferReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransferReply");
    private static final QName _ArchiveTransferRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveTransferRequestReply");
    private static final QName _AuthorizationControlAuthorityRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationControlAuthorityRequestReply");
    private static final QName _AuthorizationOriginatingAgencyRequestReply_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "AuthorizationOriginatingAgencyRequestReply");
    private static final QName _ArchiveDestructionNotification_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveDestructionNotification");
    private static final QName _ArchiveModificationNotification_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ArchiveModificationNotification");
    private static final QName _Title_QNAME = new QName("http://www.w3.org/1999/xlink", "title");
    private static final QName _Resource_QNAME = new QName("http://www.w3.org/1999/xlink", "resource");
    private static final QName _Locator_QNAME = new QName("http://www.w3.org/1999/xlink", "locator");
    private static final QName _Arc_QNAME = new QName("http://www.w3.org/1999/xlink", "arc");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorFirstName_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "FirstName");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorBirthName_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "BirthName");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorFullName_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "FullName");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorGivenName_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "GivenName");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorGender_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Gender");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorBirthDate_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "BirthDate");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorBirthPlace_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "BirthPlace");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorDeathDate_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "DeathDate");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorDeathPlace_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "DeathPlace");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorNationality_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Nationality");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorIdentifier_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Identifier");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorCorpname_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Corpname");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorValidationTime_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "ValidationTime");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorFunction_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Function");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorActivity_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Activity");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorPosition_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Position");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorRole_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Role");
    private static final QName _DescriptiveMetadataContentTypeSignatureValidatorMandate_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "Mandate");
    private static final QName _DescriptiveMetadataContentTypeSignatureSignerSigningTime_QNAME = new QName("fr:gouv:culture:archivesdefrance:seda:v2.1", "SigningTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.gouv.vitamui.commons.vitam.seda
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ManagementMetadataType }
     *
     */
    public ManagementMetadataType createManagementMetadataType() {
        return new ManagementMetadataType();
    }

    /**
     * Create an instance of {@link ManagementMetadataType.LogBook }
     *
     */
    public ManagementMetadataType.LogBook createManagementMetadataTypeLogBook() {
        return new ManagementMetadataType.LogBook();
    }

    /**
     * Create an instance of {@link DataObjectGroupType }
     *
     */
    public DataObjectGroupType createDataObjectGroupType() {
        return new DataObjectGroupType();
    }

    /**
     * Create an instance of {@link DataObjectGroupType.LogBook }
     *
     */
    public DataObjectGroupType.LogBook createDataObjectGroupTypeLogBook() {
        return new DataObjectGroupType.LogBook();
    }

    /**
     * Create an instance of {@link DataObjectGroupType.LogBook.Event }
     *
     */
    public DataObjectGroupType.LogBook.Event createDataObjectGroupTypeLogBookEvent() {
        return new DataObjectGroupType.LogBook.Event();
    }

    /**
     * Create an instance of {@link BinaryDataObjectType }
     *
     */
    public BinaryDataObjectType createBinaryDataObjectType() {
        return new BinaryDataObjectType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType }
     *
     */
    public DescriptiveMetadataContentType createDescriptiveMetadataContentType() {
        return new DescriptiveMetadataContentType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.Signature }
     *
     */
    public DescriptiveMetadataContentType.Signature createDescriptiveMetadataContentTypeSignature() {
        return new DescriptiveMetadataContentType.Signature();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.Signature.Validator }
     *
     */
    public DescriptiveMetadataContentType.Signature.Validator createDescriptiveMetadataContentTypeSignatureValidator() {
        return new DescriptiveMetadataContentType.Signature.Validator();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.CustodialHistory }
     *
     */
    public DescriptiveMetadataContentType.CustodialHistory createDescriptiveMetadataContentTypeCustodialHistory() {
        return new DescriptiveMetadataContentType.CustodialHistory();
    }

    /**
     * Create an instance of {@link ArchiveUnitType }
     *
     */
    public ArchiveUnitType createArchiveUnitType() {
        return new ArchiveUnitType();
    }

    /**
     * Create an instance of {@link KeywordsType }
     *
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link CodeType }
     *
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link AgentType }
     *
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link AcknowledgementType }
     *
     */
    public AcknowledgementType createAcknowledgementType() {
        return new AcknowledgementType();
    }

    /**
     * Create an instance of {@link ArchiveDeliveryRequestType }
     *
     */
    public ArchiveDeliveryRequestType createArchiveDeliveryRequestType() {
        return new ArchiveDeliveryRequestType();
    }

    /**
     * Create an instance of {@link ArchiveRestitutionRequestType }
     *
     */
    public ArchiveRestitutionRequestType createArchiveRestitutionRequestType() {
        return new ArchiveRestitutionRequestType();
    }

    /**
     * Create an instance of {@link ArchiveTransferType }
     *
     */
    public ArchiveTransferType createArchiveTransferType() {
        return new ArchiveTransferType();
    }

    /**
     * Create an instance of {@link ArchiveTransferRequestType }
     *
     */
    public ArchiveTransferRequestType createArchiveTransferRequestType() {
        return new ArchiveTransferRequestType();
    }

    /**
     * Create an instance of {@link AuthorizationControlAuthorityRequestType }
     *
     */
    public AuthorizationControlAuthorityRequestType createAuthorizationControlAuthorityRequestType() {
        return new AuthorizationControlAuthorityRequestType();
    }

    /**
     * Create an instance of {@link AuthorizationOriginatingAgencyRequestType }
     *
     */
    public AuthorizationOriginatingAgencyRequestType createAuthorizationOriginatingAgencyRequestType() {
        return new AuthorizationOriginatingAgencyRequestType();
    }

    /**
     * Create an instance of {@link ArchiveDeliveryRequestReplyType }
     *
     */
    public ArchiveDeliveryRequestReplyType createArchiveDeliveryRequestReplyType() {
        return new ArchiveDeliveryRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveRestitutionRequestReplyType }
     *
     */
    public ArchiveRestitutionRequestReplyType createArchiveRestitutionRequestReplyType() {
        return new ArchiveRestitutionRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveTransferReplyType }
     *
     */
    public ArchiveTransferReplyType createArchiveTransferReplyType() {
        return new ArchiveTransferReplyType();
    }

    /**
     * Create an instance of {@link ArchiveTransferRequestReplyType }
     *
     */
    public ArchiveTransferRequestReplyType createArchiveTransferRequestReplyType() {
        return new ArchiveTransferRequestReplyType();
    }

    /**
     * Create an instance of {@link AuthorizationControlAuthorityRequestReplyType }
     *
     */
    public AuthorizationControlAuthorityRequestReplyType createAuthorizationControlAuthorityRequestReplyType() {
        return new AuthorizationControlAuthorityRequestReplyType();
    }

    /**
     * Create an instance of {@link AuthorizationOriginatingAgencyRequestReplyType }
     *
     */
    public AuthorizationOriginatingAgencyRequestReplyType createAuthorizationOriginatingAgencyRequestReplyType() {
        return new AuthorizationOriginatingAgencyRequestReplyType();
    }

    /**
     * Create an instance of {@link ArchiveDestructionNotificationType }
     *
     */
    public ArchiveDestructionNotificationType createArchiveDestructionNotificationType() {
        return new ArchiveDestructionNotificationType();
    }

    /**
     * Create an instance of {@link ArchiveModificationNotificationType }
     *
     */
    public ArchiveModificationNotificationType createArchiveModificationNotificationType() {
        return new ArchiveModificationNotificationType();
    }

    /**
     * Create an instance of {@link CoverageType }
     *
     */
    public CoverageType createCoverageType() {
        return new CoverageType();
    }

    /**
     * Create an instance of {@link DataObjectOrArchiveUnitReferenceType }
     *
     */
    public DataObjectOrArchiveUnitReferenceType createDataObjectOrArchiveUnitReferenceType() {
        return new DataObjectOrArchiveUnitReferenceType();
    }

    /**
     * Create an instance of {@link EventType }
     *
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link ReferencedObjectType }
     *
     */
    public ReferencedObjectType createReferencedObjectType() {
        return new ReferencedObjectType();
    }

    /**
     * Create an instance of {@link GpsType }
     *
     */
    public GpsType createGpsType() {
        return new GpsType();
    }

    /**
     * Create an instance of {@link TextType }
     *
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link IdentifierType }
     *
     */
    public IdentifierType createIdentifierType() {
        return new IdentifierType();
    }

    /**
     * Create an instance of {@link DataObjectRefType }
     *
     */
    public DataObjectRefType createDataObjectRefType() {
        return new DataObjectRefType();
    }

    /**
     * Create an instance of {@link MessageDigestBinaryObjectType }
     *
     */
    public MessageDigestBinaryObjectType createMessageDigestBinaryObjectType() {
        return new MessageDigestBinaryObjectType();
    }

    /**
     * Create an instance of {@link BinaryObjectType }
     *
     */
    public BinaryObjectType createBinaryObjectType() {
        return new BinaryObjectType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     *
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     *
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link OrganizationDescriptiveMetadataType }
     *
     */
    public OrganizationDescriptiveMetadataType createOrganizationDescriptiveMetadataType() {
        return new OrganizationDescriptiveMetadataType();
    }

    /**
     * Create an instance of {@link SignatureType }
     *
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link TextTechnicalMetadataType }
     *
     */
    public TextTechnicalMetadataType createTextTechnicalMetadataType() {
        return new TextTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link DocumentTechnicalMetadataType }
     *
     */
    public DocumentTechnicalMetadataType createDocumentTechnicalMetadataType() {
        return new DocumentTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link ImageTechnicalMetadataType }
     *
     */
    public ImageTechnicalMetadataType createImageTechnicalMetadataType() {
        return new ImageTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link AudioTechnicalMetadataType }
     *
     */
    public AudioTechnicalMetadataType createAudioTechnicalMetadataType() {
        return new AudioTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link VideoTechnicalMetadataType }
     *
     */
    public VideoTechnicalMetadataType createVideoTechnicalMetadataType() {
        return new VideoTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link DescriptiveTechnicalMetadataType }
     *
     */
    public DescriptiveTechnicalMetadataType createDescriptiveTechnicalMetadataType() {
        return new DescriptiveTechnicalMetadataType();
    }

    /**
     * Create an instance of {@link RuleIdType }
     *
     */
    public RuleIdType createRuleIdType() {
        return new RuleIdType();
    }

    /**
     * Create an instance of {@link AccessRuleType }
     *
     */
    public AccessRuleType createAccessRuleType() {
        return new AccessRuleType();
    }

    /**
     * Create an instance of {@link DisseminationRuleType }
     *
     */
    public DisseminationRuleType createDisseminationRuleType() {
        return new DisseminationRuleType();
    }

    /**
     * Create an instance of {@link ReuseRuleType }
     *
     */
    public ReuseRuleType createReuseRuleType() {
        return new ReuseRuleType();
    }

    /**
     * Create an instance of {@link ClassificationRuleType }
     *
     */
    public ClassificationRuleType createClassificationRuleType() {
        return new ClassificationRuleType();
    }

    /**
     * Create an instance of {@link StorageRuleType }
     *
     */
    public StorageRuleType createStorageRuleType() {
        return new StorageRuleType();
    }

    /**
     * Create an instance of {@link AppraisalRuleType }
     *
     */
    public AppraisalRuleType createAppraisalRuleType() {
        return new AppraisalRuleType();
    }

    /**
     * Create an instance of {@link FormatIdentificationType }
     *
     */
    public FormatIdentificationType createFormatIdentificationType() {
        return new FormatIdentificationType();
    }

    /**
     * Create an instance of {@link FileInfoType }
     *
     */
    public FileInfoType createFileInfoType() {
        return new FileInfoType();
    }

    /**
     * Create an instance of {@link PhysicalDataObjectType }
     *
     */
    public PhysicalDataObjectType createPhysicalDataObjectType() {
        return new PhysicalDataObjectType();
    }

    /**
     * Create an instance of {@link CoreMetadataType }
     *
     */
    public CoreMetadataType createCoreMetadataType() {
        return new CoreMetadataType();
    }

    /**
     * Create an instance of {@link DimensionsType }
     *
     */
    public DimensionsType createDimensionsType() {
        return new DimensionsType();
    }

    /**
     * Create an instance of {@link MeasurementType }
     *
     */
    public MeasurementType createMeasurementType() {
        return new MeasurementType();
    }

    /**
     * Create an instance of {@link MeasurementWeightType }
     *
     */
    public MeasurementWeightType createMeasurementWeightType() {
        return new MeasurementWeightType();
    }

    /**
     * Create an instance of {@link CodeListVersionsType }
     *
     */
    public CodeListVersionsType createCodeListVersionsType() {
        return new CodeListVersionsType();
    }

    /**
     * Create an instance of {@link DataObjectPackageType }
     *
     */
    public DataObjectPackageType createDataObjectPackageType() {
        return new DataObjectPackageType();
    }

    /**
     * Create an instance of {@link AuthorizationRequestContentType }
     *
     */
    public AuthorizationRequestContentType createAuthorizationRequestContentType() {
        return new AuthorizationRequestContentType();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataType }
     *
     */
    public DescriptiveMetadataType createDescriptiveMetadataType() {
        return new DescriptiveMetadataType();
    }

    /**
     * Create an instance of {@link OperationType }
     *
     */
    public OperationType createOperationType() {
        return new OperationType();
    }

    /**
     * Create an instance of {@link OrganizationWithIdType }
     *
     */
    public OrganizationWithIdType createOrganizationWithIdType() {
        return new OrganizationWithIdType();
    }

    /**
     * Create an instance of {@link TitleEltType }
     *
     */
    public TitleEltType createTitleEltType() {
        return new TitleEltType();
    }

    /**
     * Create an instance of {@link ResourceType }
     *
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link LocatorType }
     *
     */
    public LocatorType createLocatorType() {
        return new LocatorType();
    }

    /**
     * Create an instance of {@link ArcType }
     *
     */
    public ArcType createArcType() {
        return new ArcType();
    }

    /**
     * Create an instance of {@link Simple }
     *
     */
    public Simple createSimple() {
        return new Simple();
    }

    /**
     * Create an instance of {@link Extended }
     *
     */
    public Extended createExtended() {
        return new Extended();
    }

    /**
     * Create an instance of {@link ManagementMetadataType.LogBook.Event }
     *
     */
    public ManagementMetadataType.LogBook.Event createManagementMetadataTypeLogBookEvent() {
        return new ManagementMetadataType.LogBook.Event();
    }

    /**
     * Create an instance of {@link DataObjectGroupType.LogBook.Event.DataObjectReference }
     *
     */
    public DataObjectGroupType.LogBook.Event.DataObjectReference createDataObjectGroupTypeLogBookEventDataObjectReference() {
        return new DataObjectGroupType.LogBook.Event.DataObjectReference();
    }

    /**
     * Create an instance of {@link BinaryDataObjectType.Compressed }
     *
     */
    public BinaryDataObjectType.Compressed createBinaryDataObjectTypeCompressed() {
        return new BinaryDataObjectType.Compressed();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.Writer }
     *
     */
    public DescriptiveMetadataContentType.Writer createDescriptiveMetadataContentTypeWriter() {
        return new DescriptiveMetadataContentType.Writer();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.RelatedObjectReference }
     *
     */
    public DescriptiveMetadataContentType.RelatedObjectReference createDescriptiveMetadataContentTypeRelatedObjectReference() {
        return new DescriptiveMetadataContentType.RelatedObjectReference();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.Signature.Signer }
     *
     */
    public DescriptiveMetadataContentType.Signature.Signer createDescriptiveMetadataContentTypeSignatureSigner() {
        return new DescriptiveMetadataContentType.Signature.Signer();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }
     *
     */
    public DescriptiveMetadataContentType.Signature.Validator.BirthPlace createDescriptiveMetadataContentTypeSignatureValidatorBirthPlace() {
        return new DescriptiveMetadataContentType.Signature.Validator.BirthPlace();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }
     *
     */
    public DescriptiveMetadataContentType.Signature.Validator.DeathPlace createDescriptiveMetadataContentTypeSignatureValidatorDeathPlace() {
        return new DescriptiveMetadataContentType.Signature.Validator.DeathPlace();
    }

    /**
     * Create an instance of {@link DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem }
     *
     */
    public DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem createDescriptiveMetadataContentTypeCustodialHistoryCustodialHistoryItem() {
        return new DescriptiveMetadataContentType.CustodialHistory.CustodialHistoryItem();
    }

    /**
     * Create an instance of {@link ArchiveUnitType.Management }
     *
     */
    public ArchiveUnitType.Management createArchiveUnitTypeManagement() {
        return new ArchiveUnitType.Management();
    }

    /**
     * Create an instance of {@link KeywordsType.KeywordType }
     *
     */
    public KeywordsType.KeywordType createKeywordsTypeKeywordType() {
        return new KeywordsType.KeywordType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ObjectGroupExtenstionAbstract")
    public JAXBElement<Object> createObjectGroupExtenstionAbstract(Object value) {
        return new JAXBElement<Object>(_ObjectGroupExtenstionAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherDimensionsAbstract")
    public JAXBElement<Object> createOtherDimensionsAbstract(Object value) {
        return new JAXBElement<Object>(_OtherDimensionsAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherCoreTechnicalMetadataAbstract")
    public JAXBElement<OpenType> createOtherCoreTechnicalMetadataAbstract(OpenType value) {
        return new JAXBElement<OpenType>(_OtherCoreTechnicalMetadataAbstract_QNAME, OpenType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveUnitReferenceAbstract")
    public JAXBElement<Object> createArchiveUnitReferenceAbstract(Object value) {
        return new JAXBElement<Object>(_ArchiveUnitReferenceAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherManagementAbstract")
    public JAXBElement<Object> createOtherManagementAbstract(Object value) {
        return new JAXBElement<Object>(_OtherManagementAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CodeType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "OtherCodeListAbstract")
    public JAXBElement<CodeType> createOtherCodeListAbstract(CodeType value) {
        return new JAXBElement<CodeType>(_OtherCodeListAbstract_QNAME, CodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AgentType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AgentAbstract")
    public JAXBElement<AgentType> createAgentAbstract(AgentType value) {
        return new JAXBElement<AgentType>(_AgentAbstract_QNAME, AgentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "EventAbstract")
    public JAXBElement<Object> createEventAbstract(Object value) {
        return new JAXBElement<Object>(_EventAbstract_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AcknowledgementType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Acknowledgement")
    public JAXBElement<AcknowledgementType> createAcknowledgement(AcknowledgementType value) {
        return new JAXBElement<AcknowledgementType>(_Acknowledgement_QNAME, AcknowledgementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveDeliveryRequest")
    public JAXBElement<ArchiveDeliveryRequestType> createArchiveDeliveryRequest(ArchiveDeliveryRequestType value) {
        return new JAXBElement<ArchiveDeliveryRequestType>(_ArchiveDeliveryRequest_QNAME, ArchiveDeliveryRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveRestitutionRequest")
    public JAXBElement<ArchiveRestitutionRequestType> createArchiveRestitutionRequest(ArchiveRestitutionRequestType value) {
        return new JAXBElement<ArchiveRestitutionRequestType>(_ArchiveRestitutionRequest_QNAME, ArchiveRestitutionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransfer")
    public JAXBElement<ArchiveTransferType> createArchiveTransfer(ArchiveTransferType value) {
        return new JAXBElement<ArchiveTransferType>(_ArchiveTransfer_QNAME, ArchiveTransferType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransferRequest")
    public JAXBElement<ArchiveTransferRequestType> createArchiveTransferRequest(ArchiveTransferRequestType value) {
        return new JAXBElement<ArchiveTransferRequestType>(_ArchiveTransferRequest_QNAME, ArchiveTransferRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationControlAuthorityRequest")
    public JAXBElement<AuthorizationControlAuthorityRequestType> createAuthorizationControlAuthorityRequest(AuthorizationControlAuthorityRequestType value) {
        return new JAXBElement<AuthorizationControlAuthorityRequestType>(_AuthorizationControlAuthorityRequest_QNAME, AuthorizationControlAuthorityRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationOriginatingAgencyRequest")
    public JAXBElement<AuthorizationOriginatingAgencyRequestType> createAuthorizationOriginatingAgencyRequest(AuthorizationOriginatingAgencyRequestType value) {
        return new JAXBElement<AuthorizationOriginatingAgencyRequestType>(_AuthorizationOriginatingAgencyRequest_QNAME, AuthorizationOriginatingAgencyRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDeliveryRequestReplyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveDeliveryRequestReply")
    public JAXBElement<ArchiveDeliveryRequestReplyType> createArchiveDeliveryRequestReply(ArchiveDeliveryRequestReplyType value) {
        return new JAXBElement<ArchiveDeliveryRequestReplyType>(_ArchiveDeliveryRequestReply_QNAME, ArchiveDeliveryRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveRestitutionRequestReplyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveRestitutionRequestReply")
    public JAXBElement<ArchiveRestitutionRequestReplyType> createArchiveRestitutionRequestReply(ArchiveRestitutionRequestReplyType value) {
        return new JAXBElement<ArchiveRestitutionRequestReplyType>(_ArchiveRestitutionRequestReply_QNAME, ArchiveRestitutionRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferReplyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransferReply")
    public JAXBElement<ArchiveTransferReplyType> createArchiveTransferReply(ArchiveTransferReplyType value) {
        return new JAXBElement<ArchiveTransferReplyType>(_ArchiveTransferReply_QNAME, ArchiveTransferReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveTransferRequestReplyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveTransferRequestReply")
    public JAXBElement<ArchiveTransferRequestReplyType> createArchiveTransferRequestReply(ArchiveTransferRequestReplyType value) {
        return new JAXBElement<ArchiveTransferRequestReplyType>(_ArchiveTransferRequestReply_QNAME, ArchiveTransferRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationControlAuthorityRequestReplyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationControlAuthorityRequestReply")
    public JAXBElement<AuthorizationControlAuthorityRequestReplyType> createAuthorizationControlAuthorityRequestReply(AuthorizationControlAuthorityRequestReplyType value) {
        return new JAXBElement<AuthorizationControlAuthorityRequestReplyType>(_AuthorizationControlAuthorityRequestReply_QNAME, AuthorizationControlAuthorityRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthorizationOriginatingAgencyRequestReplyType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "AuthorizationOriginatingAgencyRequestReply")
    public JAXBElement<AuthorizationOriginatingAgencyRequestReplyType> createAuthorizationOriginatingAgencyRequestReply(AuthorizationOriginatingAgencyRequestReplyType value) {
        return new JAXBElement<AuthorizationOriginatingAgencyRequestReplyType>(_AuthorizationOriginatingAgencyRequestReply_QNAME, AuthorizationOriginatingAgencyRequestReplyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveDestructionNotificationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveDestructionNotification")
    public JAXBElement<ArchiveDestructionNotificationType> createArchiveDestructionNotification(ArchiveDestructionNotificationType value) {
        return new JAXBElement<ArchiveDestructionNotificationType>(_ArchiveDestructionNotification_QNAME, ArchiveDestructionNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArchiveModificationNotificationType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ArchiveModificationNotification")
    public JAXBElement<ArchiveModificationNotificationType> createArchiveModificationNotification(ArchiveModificationNotificationType value) {
        return new JAXBElement<ArchiveModificationNotificationType>(_ArchiveModificationNotification_QNAME, ArchiveModificationNotificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleEltType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "title")
    public JAXBElement<TitleEltType> createTitle(TitleEltType value) {
        return new JAXBElement<TitleEltType>(_Title_QNAME, TitleEltType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "resource")
    public JAXBElement<ResourceType> createResource(ResourceType value) {
        return new JAXBElement<ResourceType>(_Resource_QNAME, ResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocatorType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "locator")
    public JAXBElement<LocatorType> createLocator(LocatorType value) {
        return new JAXBElement<LocatorType>(_Locator_QNAME, LocatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "arc")
    public JAXBElement<ArcType> createArc(ArcType value) {
        return new JAXBElement<ArcType>(_Arc_QNAME, ArcType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FirstName", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorFirstName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFirstName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthName", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorBirthName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorBirthName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FullName", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorFullName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFullName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "GivenName", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorGivenName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGivenName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Gender", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorGender(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGender_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthDate", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeSignatureValidatorBirthDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorBirthDate_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthPlace", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace> createDescriptiveMetadataContentTypeSignatureValidatorBirthPlace(DescriptiveMetadataContentType.Signature.Validator.BirthPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace>(_DescriptiveMetadataContentTypeSignatureValidatorBirthPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.BirthPlace.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathDate", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeSignatureValidatorDeathDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorDeathDate_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathPlace", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace> createDescriptiveMetadataContentTypeSignatureValidatorDeathPlace(DescriptiveMetadataContentType.Signature.Validator.DeathPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace>(_DescriptiveMetadataContentTypeSignatureValidatorDeathPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.DeathPlace.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Nationality", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorNationality(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorNationality_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Identifier", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorIdentifier(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorIdentifier_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Corpname", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureValidatorCorpname(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorCorpname_QNAME, String.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "ValidationTime", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeSignatureValidatorValidationTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorValidationTime_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Function", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureValidatorFunction(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorFunction_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Activity", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureValidatorActivity(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorActivity_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Position", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureValidatorPosition(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorPosition_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Role", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureValidatorRole(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorRole_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Mandate", scope = DescriptiveMetadataContentType.Signature.Validator.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureValidatorMandate(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorMandate_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Validator.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FirstName", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerFirstName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFirstName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthName", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerBirthName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorBirthName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FullName", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerFullName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFullName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "GivenName", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerGivenName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGivenName_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Gender", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerGender(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGender_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthDate", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeSignatureSignerBirthDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorBirthDate_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthPlace", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace> createDescriptiveMetadataContentTypeSignatureSignerBirthPlace(DescriptiveMetadataContentType.Signature.Validator.BirthPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace>(_DescriptiveMetadataContentTypeSignatureValidatorBirthPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.BirthPlace.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathDate", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeSignatureSignerDeathDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorDeathDate_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathPlace", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace> createDescriptiveMetadataContentTypeSignatureSignerDeathPlace(DescriptiveMetadataContentType.Signature.Validator.DeathPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace>(_DescriptiveMetadataContentTypeSignatureValidatorDeathPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.DeathPlace.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Nationality", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerNationality(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorNationality_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Identifier", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerIdentifier(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorIdentifier_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Corpname", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeSignatureSignerCorpname(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorCorpname_QNAME, String.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "SigningTime", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeSignatureSignerSigningTime(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureSignerSigningTime_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Function", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureSignerFunction(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorFunction_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Activity", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureSignerActivity(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorActivity_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Position", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureSignerPosition(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorPosition_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Role", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureSignerRole(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorRole_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Mandate", scope = DescriptiveMetadataContentType.Signature.Signer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeSignatureSignerMandate(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorMandate_QNAME, TextType.class, DescriptiveMetadataContentType.Signature.Signer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FirstName", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterFirstName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFirstName_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthName", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterBirthName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorBirthName_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FullName", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterFullName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFullName_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "GivenName", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterGivenName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGivenName_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Gender", scope = DescriptiveMetadataContentType.Writer.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterGender(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGender_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthDate", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeWriterBirthDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorBirthDate_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthPlace", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace> createDescriptiveMetadataContentTypeWriterBirthPlace(DescriptiveMetadataContentType.Signature.Validator.BirthPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace>(_DescriptiveMetadataContentTypeSignatureValidatorBirthPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.BirthPlace.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathDate", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<XMLGregorianCalendar> createDescriptiveMetadataContentTypeWriterDeathDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorDeathDate_QNAME, XMLGregorianCalendar.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathPlace", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace> createDescriptiveMetadataContentTypeWriterDeathPlace(DescriptiveMetadataContentType.Signature.Validator.DeathPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace>(_DescriptiveMetadataContentTypeSignatureValidatorDeathPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.DeathPlace.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Nationality", scope = DescriptiveMetadataContentType.Writer.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterNationality(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorNationality_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Identifier", scope = DescriptiveMetadataContentType.Writer.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterIdentifier(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorIdentifier_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Corpname", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<String> createDescriptiveMetadataContentTypeWriterCorpname(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorCorpname_QNAME, String.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Function", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeWriterFunction(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorFunction_QNAME, TextType.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Activity", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeWriterActivity(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorActivity_QNAME, TextType.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Position", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeWriterPosition(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorPosition_QNAME, TextType.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Role", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeWriterRole(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorRole_QNAME, TextType.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Mandate", scope = DescriptiveMetadataContentType.Writer.class)
    public JAXBElement<TextType> createDescriptiveMetadataContentTypeWriterMandate(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorMandate_QNAME, TextType.class, DescriptiveMetadataContentType.Writer.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FirstName", scope = AgentType.class)
    public JAXBElement<String> createAgentTypeFirstName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFirstName_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthName", scope = AgentType.class)
    public JAXBElement<String> createAgentTypeBirthName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorBirthName_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "FullName", scope = AgentType.class)
    public JAXBElement<String> createAgentTypeFullName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorFullName_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "GivenName", scope = AgentType.class)
    public JAXBElement<String> createAgentTypeGivenName(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGivenName_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Gender", scope = AgentType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAgentTypeGender(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorGender_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthDate", scope = AgentType.class)
    public JAXBElement<XMLGregorianCalendar> createAgentTypeBirthDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorBirthDate_QNAME, XMLGregorianCalendar.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.BirthPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "BirthPlace", scope = AgentType.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace> createAgentTypeBirthPlace(DescriptiveMetadataContentType.Signature.Validator.BirthPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.BirthPlace>(_DescriptiveMetadataContentTypeSignatureValidatorBirthPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.BirthPlace.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathDate", scope = AgentType.class)
    public JAXBElement<XMLGregorianCalendar> createAgentTypeDeathDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DescriptiveMetadataContentTypeSignatureValidatorDeathDate_QNAME, XMLGregorianCalendar.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptiveMetadataContentType.Signature.Validator.DeathPlace }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "DeathPlace", scope = AgentType.class)
    public JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace> createAgentTypeDeathPlace(DescriptiveMetadataContentType.Signature.Validator.DeathPlace value) {
        return new JAXBElement<DescriptiveMetadataContentType.Signature.Validator.DeathPlace>(_DescriptiveMetadataContentTypeSignatureValidatorDeathPlace_QNAME, DescriptiveMetadataContentType.Signature.Validator.DeathPlace.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Nationality", scope = AgentType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAgentTypeNationality(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorNationality_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Identifier", scope = AgentType.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAgentTypeIdentifier(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorIdentifier_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Corpname", scope = AgentType.class)
    public JAXBElement<String> createAgentTypeCorpname(String value) {
        return new JAXBElement<String>(_DescriptiveMetadataContentTypeSignatureValidatorCorpname_QNAME, String.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Function", scope = AgentType.class)
    public JAXBElement<TextType> createAgentTypeFunction(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorFunction_QNAME, TextType.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Activity", scope = AgentType.class)
    public JAXBElement<TextType> createAgentTypeActivity(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorActivity_QNAME, TextType.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Position", scope = AgentType.class)
    public JAXBElement<TextType> createAgentTypePosition(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorPosition_QNAME, TextType.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Role", scope = AgentType.class)
    public JAXBElement<TextType> createAgentTypeRole(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorRole_QNAME, TextType.class, AgentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "fr:gouv:culture:archivesdefrance:seda:v2.1", name = "Mandate", scope = AgentType.class)
    public JAXBElement<TextType> createAgentTypeMandate(TextType value) {
        return new JAXBElement<TextType>(_DescriptiveMetadataContentTypeSignatureValidatorMandate_QNAME, TextType.class, AgentType.class, value);
    }

}
