---

vitam_defaults:
  folder:
    root_path: "/vitam"
    folder_permission: "0750"
    conf_permission: "0440"
    folder_upload_permission: "0770"
    script_permission: "0750"
  users:
    vitam: vitam
    vitamdb: vitamdb
    group: vitam
  services:
    at_boot: false

# Mandatory Vitam services for VitamUI
vitam_vars:
  functional_administration:
    vitam_tenants_usage_external:
      - name: 0
        identifiers:
          - INGEST_CONTRACT
          - ACCESS_CONTRACT
          - MANAGEMENT_CONTRACT
          - ARCHIVE_UNIT_PROFILE
      - name: 1
        identifiers:
          - INGEST_CONTRACT
          - ACCESS_CONTRACT
          - MANAGEMENT_CONTRACT
          - PROFILE
          - SECURITY_PROFILE
          - CONTEXT
  access_external:
    host: "access-external.service.{{ vitam_site_name }}.{{ consul_domain }}"
    port_service: 8444
  ingest_external:
    host: "ingest-external.service.{{ vitam_site_name }}.{{ consul_domain }}"
    port_service: 8443
  collect_external:
    host: "collect-external.service.{{ vitam_site_name }}.{{ consul_domain }}"
    port_service: 8030

vitam_certs:
  vitamui:
    keystore_filename: keystore_vitamui.p12
    keystore_password: "{{ keystore_client_vitam_clients_vitamui }}"
    truststore_filename: truststore_client-vitam.p12
    truststore_password: "{{ truststore_client_vitam }}"


# Define connection settings for external / third-party Vitam instances (for COLLECT)
external_archiving_systems:

  ## Every external archiving system must have a unique id (only used alphanumeric chars, "_" or "-").
  ## Please ensure corresponding keystore/truststore files are provided :
  ##  > environments/external_archiving_systems_keystores/keystore_<archiving_system_id>.p12
  ##  > environments/external_archiving_systems_keystores/truststore_<archiving_system_id>.p12
  ## Please ensure keystore/truststore passwords are defined (in an ansible vault file):
  ##  > external_archiving_systems.keystore_password.<archiving_system_id>: <changeme>
  ##  > external_archiving_systems.truststore_password.<archiving_system_id>: <changeme>

  # client_configuration:
  #  - archiving_system_id: <ExternalEnvId>
  #    name: "EXTERNAL ENV NAME"
  #    access_external:
  #      host: <host_name>
  #      port: <port>
  #  ...

  ## By default, users have only access to referential configuration from the current Vitam instance and only for active tenant
  ## Access to other tenants and/or third party Vitam instances may be configured bellow.
  ## Use "local" as archiving_system_id to reference current Vitam instance with other tenants

  # tenant_configuration:
  # - tenant: 2
  #   external_archiving_system_references:
  #     - archiving_system_id: local
  #       tenantIds: [1, 2, 3]
  #     - archiving_system_id: <ExternalEnvId>
  #       tenantIds: [0, 2]
  # ...
