---

- name: Check for weak passwords and collect failing keys
  set_fact:
    weak_password_keys: "{{ weak_password_keys | default([]) + ([item.key] if (item.value is search('(changeit|azerty|qwerty|1234$)')) else []) }}"
  loop:
    - { key: "mongodb.admin.password", value: "{{ mongodb.admin.password }}" }
    - { key: "mongodb.localadmin.password", value: "{{ mongodb.localadmin.password }}" }
    - { key: "mongodb.system.password", value: "{{ mongodb.system.password }}" }
    - { key: "mongodb.security.password", value: "{{ mongodb.security.password }}" }
    - { key: "mongodb.iam.password", value: "{{ mongodb.iam.password }}" }
    - { key: "mongodb.discussions.password", value: "{{ mongodb.discussions.password }}" }
    - { key: "mongodb.cas.password", value: "{{ mongodb.cas.password }}" }
    - { key: "mongodb.versioning.password", value: "{{ mongodb.versioning.password }}" }
    - { key: "mongodb.archivesearch.password", value: "{{ mongodb.archivesearch.password }}" }
    - { key: "vitamui.cas_server.secret_token", value: "{{ vitamui.cas_server.secret_token }}" }
  no_log: "{{ hide_passwords_during_deploy }}"

- name: Fail if any weak passwords are found
  fail:
    msg: "The following passwords are not properly updated for production deployment: {{ weak_password_keys | join(', ') }}"
  when: weak_password_keys | length > 0
  ignore_errors: "{{ true if deployment_mode | default('prod') == 'dev' else false }}"
