# TECHNICAL PROPERTIES / DON'T put environment properties
# This property can be override by a config file give at run time with spring.config.location

spring:
  application:
    name: archive-search
  api:
    name: API Archive Search
    description: This API is used to manage Vitam's archives
    version: v1
  # This property is deprecated and will be removed in future Spring Boot versions
      # enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jmx:
    unique-names: true

management:
  endpoints:
    jmx:
      domain: archive-search
    web.exposure.include: info,health,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

swagger:
  layer: api-external
  file-path: file:../../../tools/swagger/docs/api-external/archive-search/swagger.json

gateway:
  enabled: true
