export enum ThemeDataType {
    PORTAL_MESSAGE = 'PORTAL_MESSAGE',
    PORTAL_TITLE = 'PORTAL_TITLE',
    PORTAL_LOGO = 'PORTAL_LOGO',
    HEADER_LOGO = 'HEADER_LOGO',
    FOOTER_LOGO = 'FOOTER_LOGO'
}
