---

- include_tasks: uninstall.yml
  when: syslog.name | default('filebeat') != "filebeat" and 1 == 2

- include_tasks: install.yml
  when: syslog.name | default('filebeat') == "filebeat" and 1 == 2
