serverHost: int.env-api.programmevitam.fr
serverPort: 443
secure: true
sslConfiguration :
 keystore :
  - keyPath: /vitam/conf/certs/our-keystore-env-ga.p12
    keyPassword: azerty4
 truststore :
  - keyPath: /vitam/conf/certs/our-trust-store.jks
    keyPassword: azerty10
hostnameVerification: true


