---

filebeat_version: "{{ filebeat.version | default('8.14.3') }}"
filebeat_package: "filebeat{{ '=' if ansible_os_family == 'Debian' else '-' }}{{ filebeat_version }}"

filebeat:
  processors:
    - add_host_metadata:
        when.not.contains.tags: forwarded
  config:
    ignore_older: "24h"
  system:
    enable_log: false
    enable_auth: false
  cots:
    consul:
      enable_log: true
    logstash:
      enable_log: true
    apache:
      enable_access: true
      enable_log: true
    nginx:
      enable_access: true
      enable_error: true
      enable_ingress: false
    mongodb:
      enable_log: true
  services:
    vitamui:
      api_gateway:
        enable_management: false
