---

- name: "Install {{ vitamui_struct.package_name | default(package_name) }} package"
  package:
    name: "{{ vitamui_struct.package_name | default(package_name) }}"
    state: latest
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags: update_vitamui_package
  notify: restart service
  when: force_vitamui_version is not defined and install_mode != "container"

# Force a specific version to install (even downgrade)
- block:

    - name: "Install {{ vitamui_struct.package_name | default(package_name) }} package"
      apt:
        name: "{{ vitamui_struct.package_name | default(package_name) }}={{ force_vitamui_version }}"
        force: true
        state: present
      register: result
      retries: "{{ packages_install_retries_number }}"
      until: result is succeeded
      delay: "{{ packages_install_retries_delay }}"
      tags: update_vitamui_package
      notify: restart service
      when: ansible_os_family == "Debian"

    - name: "Install {{ vitamui_struct.package_name | default(package_name) }} package"
      yum:
        name: "{{ vitamui_struct.package_name | default(package_name) }}-{{ force_vitamui_version }}"
        allow_downgrade: true
        state: present
      register: result
      retries: "{{ packages_install_retries_number }}"
      until: result is succeeded
      delay: "{{ packages_install_retries_delay }}"
      tags: update_vitamui_package
      notify: restart service
      when: ansible_os_family in ['RedHat', 'Rocky']

  when: force_vitamui_version is defined and install_mode != "container"

#### Configuration ####
- name: Check that the directories exist (must be removed when the RPM plugin will be patched)
  file:
    path: "{{ vitamui_defaults.folder.root_path | default('/vitamui') }}/{{ item }}/{{ vitamui_struct.vitamui_component }}"
    state: directory
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  with_items:
    - app
    - bin
    - conf
    - data
    - lib
    - log
    - script
    - tmp
  notify: restart service

- name: Ensure that the sysconfig sub-directory exists
  file:
    path: "{{ vitamui_folder_conf }}/sysconfig"
    state: directory
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  notify: restart service
  when: install_mode != "container"

- name: Prepare api-gateway trusted certificates
  include_tasks: prepare_api_gateway_conf.yml
  when: vitamui_struct.vitamui_component == 'api-gateway'
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- name: Deploy java_opts configuration in sysconfig subdir
  template:
    src: java_opts.j2
    dest: "{{ vitamui_folder_conf }}/sysconfig/java_opts"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.conf_permission | default('0440') }}"
  tags:
    - update_vitamui_jvmopts
    - update_vitamui_configuration
  notify: restart service
  when: install_mode != "container"

- name: get passwd for vitamui
  getent:
    database: passwd
    key: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"

- name: Deploy systemd service file
  template:
    src: vitamui-container-componentid.service.j2
    dest: "{{ '/lib/systemd/system' if ansible_os_family == 'Debian' else '/usr/lib/systemd/system' }}/vitamui-{{ vitamui_struct.vitamui_component }}.service"
    owner: "root"
    group: "root"
    mode: "0644"
  tags: update_vitamui_configuration
  notify: restart service
  when: install_mode == "container"

- name: Deploy logback.xml configuration files
  template:
    src: logback.xml.j2
    dest: "{{ vitamui_folder_conf }}/logback.xml"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.conf_permission | default('0440') }}"
  tags: update_vitamui_configuration
  notify: restart service

- name: Deploy specific configuration files
  template:
    src: "{{ item }}"
    dest: "{{ vitamui_folder_conf }}/{{ item | basename | regex_replace('\\.j2$') }}"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.conf_permission | default('0440') }}"
  with_fileglob:
    - "{{ role_path }}/templates/{{ vitamui_struct.vitamui_component }}/*"
  #no_log: "{{ hide_passwords_during_deploy }}"
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates # Mandatory to update configuration file containing keystore password
  notify: restart service

- name: "Copy {{ vitamui_struct.service_name | default(service_name) }} jks keystore (server)"
  copy:
    src: "{{ inventory_dir }}/keystores/vitamui-services/server/{{ vitamui_struct.vitamui_component }}/keystore_{{ vitamui_struct.vitamui_component }}.jks"
    dest: "{{ vitamui_folder_conf }}/keystore_{{ vitamui_struct.service_name | default(service_name) }}.jks"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  when:
    - vitamui_struct.secure | default(secure) | lower == 'true'
    - lookup('pipe', 'test -f {{ inventory_dir }}/keystores/vitamui-services/server/{{ vitamui_struct.vitamui_component }}/keystore_{{ vitamui_struct.vitamui_component }}.jks || echo nofile') == ''
  tags: update_vitamui_certificates
  notify: restart service

- name: "Copy {{ vitamui_struct.service_name | default(service_name) }} jks keystore (client)"
  copy:
    src: "{{ inventory_dir }}/keystores/vitamui-services/clients/{{ vitamui_struct.vitamui_component }}/keystore_{{ vitamui_struct.vitamui_component }}.jks"
    dest: "{{ vitamui_folder_conf }}/keystore_client_{{ vitamui_struct.service_name | default(service_name) }}.jks"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  when:
    - vitamui_struct.secure | default(secure) | lower == 'true'
    - lookup('pipe', 'test -f {{ inventory_dir }}/keystores/vitamui-services/clients/{{ vitamui_struct.vitamui_component }}/keystore_{{ vitamui_struct.vitamui_component }}.jks || echo nofile') == ''
  tags: update_vitamui_certificates
  notify: restart service

# Copy the trustore for all vitamui components in order to communicate between them.
- name: Copy vitamui-services truststore
  copy:
    src: "{{ inventory_dir }}/keystores/vitamui-services/truststore_vitamui.jks"
    dest: "{{ vitamui_folder_conf }}/truststore_vitamui.jks"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  when:
    - vitamui_struct.secure | default(secure) | lower == 'true'
    - vitamui_certificate_type | default('none') | lower == 'vitamui-services'
    - lookup('pipe', 'test -f {{ inventory_dir }}/keystores/vitamui-services/truststore_vitamui.jks || echo nofile') == ''
  tags: update_vitamui_certificates
  notify: restart service

# Copy the truststore for all external API in order to communicate with vitamui components (ui, external APIs, cas) and externals apps.
- name: Copy external truststore
  copy:
    src: "{{ inventory_dir }}/keystores/client-{{ vitamui_certificate_type }}/truststore_{{ vitamui_certificate_type }}.jks"
    dest: "{{ vitamui_folder_conf }}/truststore_{{ vitamui_certificate_type }}.jks"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  when:
    - vitamui_struct.secure | default(secure) | lower == 'true'
    - vitamui_certificate_type | default('none') | lower == 'external'
    - lookup('pipe', 'test -f {{ inventory_dir }}/keystores/client-{{ vitamui_certificate_type }}/truststore_{{ vitamui_certificate_type }}.jks || echo nofile') == ''
  tags: update_vitamui_certificates
  notify: restart service

- name: "Execute sub-tasks for the component: {{ vitamui_struct.vitamui_component }}"
  include_tasks: "{{ vitamui_struct.vitamui_component }}.yml"
  when: lookup('pipe', 'test -f {{ role_path }}/tasks/{{ vitamui_struct.vitamui_component }}.yml || echo nofile') == ''
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- meta: flush_handlers
  tags: always

- name: test service & debug if necessary
  block:

    - name: "Ensure {{ vitamui_struct.service_name | default(service_name) }} service is started"
      service:
        name: "{{ vitamui_struct.service_name | default(service_name) }}"
        state: started
        enabled: "{{ vitamui_struct.at_boot | default(at_boot) }}"

    - name: Check whether service is listening on service port (tcp check)
      wait_for:
        host: "{{ ip_service }}"
        port: "{{ vitamui_struct.port_service }}"
        timeout: "{{ vitamui_struct.services.start_timeout | default(start_timeout) }}"
        state: started

    - name: Check whether service is listening on admin port (tcp check)
      wait_for:
        host: "{{ ip_admin }}"
        port: "{{ vitamui_struct.port_admin }}"
        timeout: "{{ vitamui_struct.services.start_timeout | default(start_timeout) }}"
        state: started

    - name: "Check if {{ vitamui_struct.service_name | default(service_name) }} service is listening on admin port (http check)"
      uri:
        url: "http://{{ ip_admin }}:{{ vitamui_struct.port_admin }}/actuator/health"
      register: result
      until:
        - result.status is defined
        - result.status == 200
      retries: "{{ vitamui_defaults.services.status_retries_number }}"
      delay: "{{ vitamui_defaults.services.status_retries_delay }}"

    - name: "Check {{ vitamui_struct.service_name | default(service_name) }} service health in local consul agent"
      uri:
        url: "http://{{ (inventory_hostname in groups['hosts_vitamui_consul_server']) | ternary(hostvars[inventory_hostname]['ip_admin'], '127.0.0.1') }}:8500/v1/agent/health/service/name/{{ vitamui_struct.service_name | default(service_name) }}"
      register: result
      until:
        - result.status is defined
        - result.status == 200
      retries: "{{ vitamui_defaults.services.status_retries_number }}"
      delay: "{{ vitamui_defaults.services.status_retries_delay }}"

  tags: always

  rescue:

    - name: getting error logs
      shell: "journalctl --reverse --lines 100 -xu {{ vitamui_struct.service_name | default(service_name) }}"
      register: journalctl_logs
    - name: printing error logs
      fail:
        msg: "{{ journalctl_logs.stdout_lines }}"
