- name: Copy vitam certificates
  copy:
    src: "{{ item }}"
    dest: "{{ vitamui_folder_conf }}/{{ item | basename }}"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  with_fileglob:
    - "{{ inventory_dir }}/keystores/client-vitam/*.*"
  when: vitam_cert is defined
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates
  notify: restart service

- name: List external Vitam systems
  set_fact:
    external_system_ids: "{{ external_archiving_systems.client_configuration | default([]) | map(attribute='archiving_system_id') | list }}"
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- name: List existing external archiving system keystores
  find:
    paths: "{{ vitamui_folder_conf }}"
    patterns: "keystore_external_archiving_system_*.p12"
    file_type: file
  register: found_external_keystores
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- name: List existing external archiving system truststores
  find:
    paths: "{{ vitamui_folder_conf }}"
    patterns: "truststore_external_archiving_system_*.p12"
    file_type: file
  register: found_external_truststores
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- name: Copy external archiving system keystores
  copy:
    src: "{{ inventory_dir }}/keystore_external_archiving_systems/keystore_{{ item }}.p12"
    dest: "{{ vitamui_folder_conf }}/keystore_external_archiving_system_{{ item }}.p12"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  with_items: "{{ external_system_ids }}"
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates
  notify: restart service

- name: Copy external archiving system truststores
  copy:
    src: "{{ inventory_dir }}/keystore_external_archiving_systems/truststore_{{ item }}.p12"
    dest: "{{ vitamui_folder_conf }}/truststore_external_archiving_system_{{ item }}.p12"
    owner: "{{ vitamui_defaults.users.vitamui | default('vitamui') }}"
    group: "{{ vitamui_defaults.users.group | default('vitamui') }}"
    mode: "{{ vitamui_defaults.folder.folder_permission | default('0750') }}"
  with_items: "{{ external_system_ids }}"
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates
  notify: restart service

- name: Delete obsolete external archiving system keystores
  file:
    path: "{{ vitamui_folder_conf }}/keystore_external_archiving_system_{{ item }}.p12"
    state: absent
  loop: "{{ found_external_keystores.files | map(attribute='path') | map('basename') | map('regex_replace', '^keystore_external_archiving_system_(.*)\\.p12$', '\\1') | list | difference(external_system_ids) }}"
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- name: Delete obsolete external archiving system truststores
  file:
    path: "{{ vitamui_folder_conf }}/truststore_external_archiving_system_{{ item }}.p12"
    state: absent
  loop: "{{ found_external_truststores.files | map(attribute='path') | map('basename') | map('regex_replace', '^truststore_fexternal_archiving_system_(.*)\\.p12$', '\\1') | list | difference(external_system_ids) }}"
  tags:
    - update_vitamui_configuration
    - update_vitamui_certificates

- include: copy_internal_ontology_fields.yml
  tags: update_vitamui_configuration
