---

- hosts: hosts_vitamui_api_gateway
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    app_default_root_path: "/vitamui"
    vitamui_struct: "{{ vitamui.api_gateway }}"
    vitamui_certificate_type: "server"
    password_keystore: "{{ keystores_server_api_gateway }}"
    password_truststore: "{{ truststores_server }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
    consul_tags: "api-gateway, api, internal"

- hosts: hosts_ui_portal
  tasks:
    - include_role:
        name: assets_copy
      vars:
        asset_path: "{{ root_path }}/data/{{ frontend_app.name }}/package/assets"
        asset_favicon_path: "{{ root_path }}/data/{{ frontend_app.name }}/package"
        asset_user: "{{ frontend_user | default('nginx') }}"
        asset_group: "{{ frontend_group | default('nginx') }}"
      with_items:
        - "{{frontend.apps}}"
      loop_control:
        loop_var: frontend_app
      when: gateway.enabled | default(False)

- hosts: hosts_ui_identity
  tasks:
    - include_role:
        name: assets_copy
      vars:
        asset_path: "{{ root_path }}/data/{{ frontend_app.name }}/package/assets"
        asset_favicon_path: "{{ root_path }}/data/{{ frontend_app.name }}/package"
        asset_user: "{{ frontend_user | default('nginx') }}"
        asset_group: "{{ frontend_group | default('nginx') }}"
      with_items:
        - "{{frontend.apps}}"
      loop_control:
        loop_var: frontend_app
      when: gateway.enabled | default(False)

- hosts: hosts_ui_identity_admin
  tasks:
    - include_role:
        name: assets_copy
      vars:
        asset_path: "{{ root_path }}/data/{{ frontend_app.name }}/package/assets"
        asset_favicon_path: "{{ root_path }}/data/{{ frontend_app.name }}/package"
        asset_user: "{{ frontend_user | default('nginx') }}"
        asset_group: "{{ frontend_group | default('nginx') }}"
      with_items:
        - "{{frontend.apps}}"
      loop_control:
        loop_var: frontend_app
      when: gateway.enabled | default(False)

# - hosts: hosts_ui_referential
#   tasks:
#     - include_role:
#         name: assets_copy
#       vars:
#         asset_path: "{{ root_path }}/data/{{ frontend_app.name }}/package/assets"
#         asset_favicon_path: "{{ root_path }}/data/{{ frontend_app.name }}/package"
#         asset_user: "{{ frontend_user | default('nginx') }}"
#         asset_group: "{{ frontend_group | default('nginx') }}"
#       with_items:
#         - "{{frontend.apps}}"
#       loop_control:
#         loop_var: frontend_app
#       when: gateway.enabled | default(False)

- hosts: hosts_ui_portal
  roles:
    - role: nginx-webapp
      vars:
        frontend_role_goal: "install"
        frontend_application_version: "5.4.0-SNAPSHOT" #"{{ app_version }}"
        frontend_application_name: "{{ hostvars[inventory_hostname]['ui_portal']['frontend_name'] }}"
      when: gateway.enabled | default(False)

- hosts: hosts_ui_identity
  roles:
    - role: nginx-webapp
      vars:
        frontend_role_goal: "install"
        frontend_application_version: "5.4.0-SNAPSHOT" #"{{ app_version }}"
        frontend_application_name: "{{ hostvars[inventory_hostname]['ui_identity']['frontend_name'] }}"
      when: gateway.enabled | default(False)

- hosts: hosts_ui_identity_admin
  roles:
    - role: nginx-webapp
      vars:
        frontend_role_goal: "install"
        frontend_application_version: "5.4.0-SNAPSHOT" #"{{ app_version }}"
        frontend_application_name: "{{ hostvars[inventory_hostname]['ui_identity_admin']['frontend_name'] }}"
      when: gateway.enabled | default(False)

# - hosts: hosts_ui_referential
#   roles:
#     - role: nginx-webapp
#       vars:
#         frontend_role_goal: "install"
#         frontend_application_version: "5.4.0-SNAPSHOT" #"{{ app_version }}"
#         frontend_application_name: "{{ hostvars[inventory_hostname]['ui_referential']['frontend_name'] }}"
#       when: gateway.enabled | default(False)
