---
- hosts: hosts_vitamui_archive_search
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.archive_search }}"
    vitamui_certificate_type: external
    password_keystore_server: "{{ keystore_server_vitamui_services_archive_search }}"
    password_keystore_client: "{{ keystore_client_vitamui_services_archive_search }}"
    password_truststore: "{{ truststore_client_external }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
