---
- hosts: hosts_vitamui_ingest
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.ingest }}"
    password_keystore_server: "{{ keystores_server_vitamui_services_ingest }}"
    password_keystore_client: "{{ keystores_client_vitamui_services_ingest }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
