---
- hosts: hosts_vitamui_referential
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.referential }}"
    password_keystore_server: "{{ keystores_server_vitamui_services_referential }}"
    password_keystore_client: "{{ keystores_client_vitamui_services_referential }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
