---
- hosts: hosts_vitamui_referential
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.referential }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
