# Ingest external calls VITAM
- hosts: hosts_vitamui_ingest_external
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.ingest_external }}"
    vitamui_certificate_type: external
    password_keystore: "{{ keystores_server_ingest_external }}"
    password_truststore: "{{ truststores_server }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
    consul_tags: "ingest-external, api"
