---

# Internal apps
- hosts: hosts_vitamui_security
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.security }}"
    password_keystore_server: "{{ keystores_server_vitamui_services_security }}"
  tags: security

# External apps
- hosts: hosts_vitamui_iam
  gather_facts: no
  any_errors_fatal: true
  roles:
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.iam }}"
    password_keystore_server: "{{ keystores_server_vitamui_services_iam }}"
    password_keystore_client: "{{ keystores_client_vitamui_services_iam }}"
    vitam_cert: "{{ vitam_certs.vitamui }}"
  tags: iam

- hosts: hosts_cas_server
  gather_facts: no
  any_errors_fatal: true
  roles:
    - assets_copy
    - vitamui
  vars:
    vitamui_struct: "{{ vitamui.cas_server }}"
    password_keystore_server: "{{ keystores_server_vitamui_services_cas_server }}"
    password_keystore_client: "{{ keystores_client_vitamui_services_cas_server }}"
  tags: cas-server
