---
- name: restart consul
  service:
    name: "{{ consul.service_name | default('vitam-consul') }}"
    state: reloaded
  listen: restart consul

- name: restart the service
  service:
    name: "{{ service_name }}"
    state: restarted
  listen: restart service
