<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <artifactId>iam-client</artifactId>
    <packaging>jar</packaging>
    <name>VITAMUI IAM API Client OpenAPI</name>

    <parent>
        <groupId>fr.gouv.vitamui</groupId>
        <artifactId>api-iam</artifactId>
        <version>9.0.1-SNAPSHOT</version>
    </parent>

    <properties>
        <!-- make iam-client on jdk 17 temporarily -->
        <!-- current Cas version use an incompatible Spring boot version 2.7.18 with java 21,
        that's why we keep CAS in JAVA 17, and all dependencies as iam-client and commons that are compiled in Java 21 with target java 17-->
        <java.version>21</java.version>
        <java.release>17</java.release>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <maven.compiler.release>17</maven.compiler.release>
    </properties>

    <build>
        <plugins>
            <!-- OpenAPI Generator Plugin -->
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>${openapi-generator-maven-plugin.version}</version>
                <executions>
                    <execution>
                        <id>generate-client</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- TODO: Swagger file should be generated during build -->
                            <inputSpec>${project.basedir}/src/main/resources/swagger.yaml</inputSpec>
                            <generatorName>java</generatorName>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <apiPackage>fr.gouv.vitamui.iam.openapiclient</apiPackage>
                            <generateModelTests>false</generateModelTests>
                            <generateModels>false</generateModels>
                            <generateApiTests>false</generateApiTests>
                            <modelPackage>fr.gouv.vitamui.iam.openapiclient.domain</modelPackage>
                            <invokerPackage>fr.gouv.vitamui.iam.openapiclient.invoker</invokerPackage>
                            <library>resttemplate</library> <!-- ou autre: okhttp-gson, webclient, retrofit2 -->
                            <removeOperationIdPrefix>true</removeOperationIdPrefix>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                                <useJakartaEe>true</useJakartaEe>
                                <useAbstractionForFiles>true</useAbstractionForFiles>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <!-- Pour inclure les sources générées dans le build -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/openapi/src/main/java</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>fr.gouv.vitamui</groupId>
            <artifactId>iam-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitamui.commons</groupId>
            <artifactId>commons-api</artifactId>
        </dependency>
        <dependency>
            <groupId>fr.gouv.vitamui.commons</groupId>
            <artifactId>commons-vitam</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>jackson-databind-nullable</artifactId>
            <version>0.2.6</version>
        </dependency>
    </dependencies>

</project>
