/*
 * Copyright French Prime minister Office/SGMAP/DINSIC/Vitam Program (2019-2022)
 * and the signatories of the "VITAM - Accord du Contributeur" agreement.
 *
 * contact@programmevitam.fr
 *
 * This software is a computer program whose purpose is to implement
 * implement a digital archiving front-office system for the secure and
 * efficient high volumetry VITAM solution.
 *
 * This software is governed by the CeCILL-C license under French law and
 * abiding by the rules of distribution of free software.  You can  use,
 * modify and/ or redistribute the software under the terms of the CeCILL-C
 * license as circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and  rights to copy,
 * modify and redistribute granted by the license, users are provided only
 * with a limited warranty  and the software's author,  the holder of the
 * economic rights,  and the successive licensors  have only  limited
 * liability.
 *
 * In this respect, the user's attention is drawn to the risks associated
 * with loading,  using,  modifying and/or developing or reproducing the
 * software by the user in light of its specific status of free software,
 * that may mean  that it is complicated to manipulate,  and  that  also
 * therefore means  that it is reserved for developers  and  experienced
 * professionals having in-depth computer knowledge. Users are therefore
 * encouraged to load and test the software's suitability as regards their
 * requirements in conditions enabling the security of their systems and/or
 * data to be ensured and,  more generally, to use and operate it in the
 * same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-C license and that you accept its terms.
 */
import { Collection, ProfiledSchemaElement } from 'vitamui-library';

export const schema: ProfiledSchemaElement[] = [
  {
    id: null,
    Path: 'Identifier',
    StringSize: 'SHORT',
    Cardinality: 'ONE_REQUIRED',
    FieldName: 'Identifier',
    ShortName: 'AGENCY.LABEL.IDENTIFIER',
    Description: 'AGENCY.LABEL.IDENTIFIER',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'Identifier',
    ApiField: 'identifier',
    Type: 'KEYWORD',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'identifier',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'Name',
    StringSize: 'SHORT',
    Cardinality: 'ONE_REQUIRED',
    FieldName: 'Name',
    ShortName: 'AGENCY.LABEL.NAME',
    Description: 'AGENCY.LABEL.NAME',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'Name',
    ApiField: 'name',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'name',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'EntityType',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'EntityType',
    ShortName: 'AGENCY.LABEL.ENTITY_TYPE',
    Description: 'AGENCY.LABEL.ENTITY_TYPE',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'EntityType',
    ApiField: 'EntityType',
    Type: 'KEYWORD',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'EntityType',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'NameEntryParallel',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'NameEntryParallel',
    ShortName: 'AGENCY.LABEL.NAME_ENTRY_PARALLEL',
    Description: 'AGENCY.LABEL.NAME_ENTRY_PARALLEL',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'NameEntryParallel',
    ApiField: 'NameEntryParallel',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'NameEntryParallel',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'AuthorizedForm',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'AuthorizedForm',
    ShortName: 'AGENCY.LABEL.AUTHORIZED_FORM',
    Description: 'AGENCY.LABEL.AUTHORIZED_FORM',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'AuthorizedForm',
    ApiField: 'AuthorizedForm',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'AuthorizedForm',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'AlternativeForm',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'AlternativeForm',
    ShortName: 'AGENCY.LABEL.ALTERNATIVE_FORM',
    Description: 'AGENCY.LABEL.ALTERNATIVE_FORM',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'AlternativeForm',
    ApiField: 'AlternativeForm',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'AlternativeForm',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'EntityId',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'EntityId',
    ShortName: 'AGENCY.LABEL.ENTITY_ID',
    Description: 'AGENCY.LABEL.ENTITY_ID',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'EntityId',
    ApiField: 'EntityId',
    Type: 'KEYWORD',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'EntityId',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'FromDate',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'FromDate',
    ShortName: 'AGENCY.LABEL.FROM_DATE',
    Description: 'AGENCY.LABEL.FROM_DATE',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'FromDate',
    ApiField: 'FromDate',
    Type: 'DATE',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'FromDate',
    DataType: 'DATETIME',
  },
  {
    id: null,
    Path: 'ToDate',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'ToDate',
    ShortName: 'AGENCY.LABEL.TO_DATE',
    Description: 'AGENCY.LABEL.TO_DATE',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'ToDate',
    ApiField: 'ToDate',
    Type: 'DATE',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'ToDate',
    DataType: 'DATETIME',
  },
  {
    id: null,
    Path: 'Functions',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'Functions',
    ShortName: 'AGENCY.LABEL.FUNCTIONS',
    Description: 'AGENCY.LABEL.FUNCTIONS',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'Functions',
    ApiField: 'Functions',
    Type: 'KEYWORD',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'Functions',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'BiogHist',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'BiogHist',
    ShortName: 'AGENCY.LABEL.BIOGHIST',
    Description: 'AGENCY.LABEL.BIOGHIST',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'BiogHist',
    ApiField: 'BiogHist',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'BiogHist',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,5000}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_5000',
    },
  },
  {
    id: null,
    Path: 'Places',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'Places',
    ShortName: 'AGENCY.LABEL.PLACES',
    Description: 'AGENCY.LABEL.PLACES',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'Places',
    ApiField: 'Places',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'Places',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'LegalStatuses',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'LegalStatuses',
    ShortName: 'AGENCY.LABEL.LEGAL_STATUSES',
    Description: 'AGENCY.LABEL.LEGAL_STATUSES',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'LegalStatuses',
    ApiField: 'LegalStatuses',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'LegalStatuses',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'Mandates',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'Mandates',
    ShortName: 'AGENCY.LABEL.MANDATES',
    Description: 'AGENCY.LABEL.MANDATES',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'Mandates',
    ApiField: 'Mandates',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'Mandates',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,5000}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_5000',
    },
  },
  {
    id: null,
    Path: 'StructureOrGenealogy',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'StructureOrGenealogy',
    ShortName: 'AGENCY.LABEL.STRUCTURE_OR_GENEALOGY',
    Description: 'AGENCY.LABEL.STRUCTURE_OR_GENEALOGY',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'StructureOrGenealogy',
    ApiField: 'StructureOrGenealogy',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'StructureOrGenealogy',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,5000}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_5000',
    },
  },
  {
    id: null,
    Path: 'GeneralContext',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'GeneralContext',
    ShortName: 'AGENCY.LABEL.GENERAL_CONTEXT',
    Description: 'AGENCY.LABEL.GENERAL_CONTEXT',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'GeneralContext',
    ApiField: 'GeneralContext',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'GeneralContext',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,5000}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_5000',
    },
  },
  {
    id: null,
    Path: 'CreationDate',
    StringSize: 'SHORT',
    Cardinality: 'ONE_REQUIRED',
    FieldName: 'CreationDate',
    ShortName: 'AGENCY.LABEL.CREATION_DATE',
    Description: 'AGENCY.LABEL.CREATION_DATE',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'CreationDate',
    ApiField: 'CreationDate',
    Type: 'DATE',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'CreationDate',
    DataType: 'DATETIME',
  },
  {
    id: null,
    Path: 'UpdateDate',
    StringSize: 'SHORT',
    Cardinality: 'ONE_REQUIRED',
    FieldName: 'UpdateDate',
    ShortName: 'AGENCY.LABEL.UPDATE_DATE',
    Description: 'AGENCY.LABEL.UPDATE_DATE',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'UpdateDate',
    ApiField: 'UpdateDate',
    Type: 'DATE',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'UpdateDate',
    DataType: 'DATETIME',
  },
  {
    id: null,
    Path: 'MaintenanceStatus',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'MaintenanceStatus',
    ShortName: 'AGENCY.LABEL.MAINTENANCE_STATUS',
    Description: 'AGENCY.LABEL.MAINTENANCE_STATUS',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'MaintenanceStatus',
    ApiField: 'MaintenanceStatus',
    Type: 'KEYWORD',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'MaintenanceStatus',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'LocalStatus',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'LocalStatus',
    ShortName: 'AGENCY.LABEL.LOCAL_STATUS',
    Description: 'AGENCY.LABEL.LOCAL_STATUS',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'LocalStatus',
    ApiField: 'LocalStatus',
    Type: 'KEYWORD',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'LocalStatus',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,50}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_50',
    },
  },
  {
    id: null,
    Path: 'Sources',
    StringSize: 'SHORT',
    Cardinality: 'MANY',
    FieldName: 'Sources',
    ShortName: 'AGENCY.LABEL.SOURCES',
    Description: 'AGENCY.LABEL.SOURCES',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'Sources',
    ApiField: 'Sources',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'Sources',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,5000}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_5000',
    },
  },
  {
    id: null,
    Path: 'EventDescription',
    StringSize: 'SHORT',
    Cardinality: 'ONE',
    FieldName: 'EventDescription',
    ShortName: 'AGENCY.LABEL.EVENT_DESCRIPTION',
    Description: 'AGENCY.LABEL.EVENT_DESCRIPTION',
    CreationDate: null,
    LastUpdate: null,
    SedaField: 'EventDescription',
    ApiField: 'EventDescription',
    Type: 'TEXT',
    Origin: 'INTERNAL',
    Collection: Collection.AGENCY,
    SedaVersions: [],
    Category: 'DESCRIPTION',
    ApiPath: 'EventDescription',
    DataType: 'STRING',
    Control: {
      Type: 'REGEX',
      Value: '.{1,5000}',
      Comment: 'AGENCY.HINT.MAX_LENGTH_5000',
    },
  },
];
