---

- name: check whether VITAMUI parent dir already exists
  stat:
    path: "{{ vitamui_defaults.folder.root_path }}"
  register: root_dir

- name: check if VITAMUI parent dir is a symlink
  copy:
    content: "root vitamui dir is symlink"
    dest: "{{ inventory_dir }}/troubleshoot/{{ inventory_hostname }}/vitamui_root_dir_symlink.txt"
  delegate_to: localhost
  when: root_dir.stat.islnk is defined and root_dir.stat.islnk == "true"
