ME_CONFIG_MONGODB_SERVER: "CHANGEME"
ME_CONFIG_MONGODB_PORT: "CHANGEME"
ME_CONFIG_SITE_BASEURL: "/"
ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
ME_CONFIG_MONGODB_ADMINUSERNAME: "CHANGEME"
ME_CONFIG_MONGODB_ADMINPASSWORD: "CHANGEME"

