<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>fr.gouv.vitamui</groupId>
    <artifactId>bom</artifactId>
    <version>9.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>VITAMUI BOM</name>
    <description>${project.artifactId}</description>

    <properties>
        <!-- Dependencies version -->
        <antisamy.version>1.7.5</antisamy.version>
        <apache.commons.codec.version>1.17.2</apache.commons.codec.version>
        <apache.pdfbox.version>2.0.31</apache.pdfbox.version>
        <bouncycastle.version>1.83</bouncycastle.version>
        <cas.version>7.0.10.1</cas.version>
        <commons.beanutils.version>1.9.4</commons.beanutils.version>
        <commons.collections4.version>4.4</commons.collections4.version>
        <commons.compress.version>1.26.1</commons.compress.version>
        <commons.fileupload.version>1.6.0</commons.fileupload.version>
        <commons.io.version>2.16.0</commons.io.version>
        <commons.text.version>1.11.0</commons.text.version>
        <cucumber.version>5.6.0</cucumber.version>
        <esapi.version>2.7.0.0</esapi.version>
        <fake.sftp.server.rule.version>2.0.1</fake.sftp.server.rule.version>
        <fop.version>2.4</fop.version>
        <freemarker.upgraded.version>2.3.30</freemarker.upgraded.version>
        <glassfish.jaxb.version>3.0.2</glassfish.jaxb.version>
        <gson.version>2.10.1</gson.version>
        <hibernate.validatior.version>8.0.1.Final</hibernate.validatior.version>
        <http.client.version>5.4.4</http.client.version>
        <http.core.version>5.3.4</http.core.version>
        <istack-commons-runtime.version>4.0.0-M2</istack-commons-runtime.version>
        <jackson.version>2.21.1</jackson.version>
        <jackson-annotation.version>2.21</jackson-annotation.version>
        <jaeger.tracing.version>3.3.1</jaeger.tracing.version>
        <jakarta.el.version>5.0.1</jakarta.el.version>
        <jakarta.mail.version>2.0.1</jakarta.mail.version>
        <jakarta.xml.binding.version>4.0.2</jakarta.xml.binding.version>
        <javassist.version>3.30.2-GA</javassist.version>
        <jakarta.servlet.version>6.0.0</jakarta.servlet.version>
        <jakarta.validation.api.version>3.0.2</jakarta.validation.api.version>
        <jakarta.ws.rs.version>3.1.0</jakarta.ws.rs.version>
        <jaxb.core.version>2.3.0.1</jaxb.core.version>
        <jaxb.impl.version>3.0.0-M1</jaxb.impl.version>
        <jaxb.version>2.4.0-b180830.0359</jaxb.version>
        <jaxp-api.version>1.4.5</jaxp-api.version>
        <jlibs.version>3.0.1</jlibs.version>
        <json-sanitize.version>1.2.3</json-sanitize.version>
        <json.version>20240303</json.version>
        <jsonassert.version>1.5.0</jsonassert.version>
        <juli.to.slf4j.version>1.1.1</juli.to.slf4j.version>
        <logback.version>1.4.14</logback.version>
        <lombok.version>1.18.38</lombok.version>
        <mapstruct.version>1.3.0.Final</mapstruct.version>
        <micrometer.version>1.13.15</micrometer.version>
        <nio.multipart.parser.version>1.1.0</nio.multipart.parser.version>
        <opencsv.version>5.4</opencsv.version>
        <org.apache.odftoolkit.version>0.8.2-incubating</org.apache.odftoolkit.version>
        <org.odftoolkit.version>0.8.7</org.odftoolkit.version>
        <pac4j.version>6.3.3</pac4j.version>
        <podam.version>7.2.5.RELEASE</podam.version>
        <poi.version>5.5.1</poi.version>
        <selma.version>1.0</selma.version>
        <serenity-spring.version>3.3.10</serenity-spring.version>
        <serenity.cucumber.version>2.2.6</serenity.cucumber.version>
        <serenity.version>3.3.10</serenity.version>
        <slf4j.version>2.0.9</slf4j.version>
        <spring-cloud-dependencies.version>2025.0.0</spring-cloud-dependencies.version>
        <spring-security-cas.version>6.2.8</spring-security-cas.version>
        <swagger.version>3.0.0</swagger.version>
        <testcontainers.version>1.21.4</testcontainers.version>
        <thaiopensource.jing.version>20220510</thaiopensource.jing.version>
        <vitam.version>9.1.0-SNAPSHOT</vitam.version>
        <xdocreport.version>2.2.0</xdocreport.version>
        <xerces.version>2.12.2</xerces.version>
        <xercesImpl-xsd11.version>2.12-beta-r1667115</xercesImpl-xsd11.version>
        <xml-resolver.version>1.2</xml-resolver.version>
        <xml.apis-version>2.0.2</xml.apis-version>
        <xml.resolver.version>1.2</xml.resolver.version>
        <xom.version>1.3.9</xom.version>
        <springdoc-openapi-starter-webmvc-ui.version>2.8.9</springdoc-openapi-starter-webmvc-ui.version>

        <!--Plugins-->
        <spotless-maven-plugin.version>2.43.0</spotless-maven-plugin.version>
        <spotless.check.skip>true</spotless.check.skip>
    </properties>

    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <!-- Gestion des dépendances -->
    <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    <dependencyManagement>
        <dependencies>
            <!-- VitamUI -->
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-api</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-logbook</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-mongo</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-rest</artifactId>
                <version>${project.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>fr.gouv.vitam</groupId>
                        <artifactId>logbook-common</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-utils</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-vitam</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>referential-commons</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>referential-commons</artifactId>
                <type>test-jar</type>
                <scope>test</scope>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>referential</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>referential-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>ingest</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>archive-search-commons</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>archive-search</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>collect</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>collect-client</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>iam-commons</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>iam-commons</artifactId>
                <type>test-jar</type>
                <scope>test</scope>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>iam-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>iam-security</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>security-client-legacy</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>security-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>security-commons</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>pastis-commons</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>pastis-client</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitamui</groupId>
                <artifactId>pastis</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.opengis.cite.xerces</groupId>
                <artifactId>xercesImpl-xsd11</artifactId>
                <version>${xercesImpl-xsd11.version}</version>
            </dependency>

            <dependency>
                <groupId>org.relaxng</groupId>
                <artifactId>jing</artifactId>
                <version>${thaiopensource.jing.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>xml-apis</groupId>
                        <artifactId>xml-apis</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>net.sf.saxon</groupId>
                        <artifactId>saxon</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>xerces</groupId>
                        <artifactId>xercesImpl</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>javax.xml.parsers</groupId>
                <artifactId>jaxp-api</artifactId>
                <version>${jaxp-api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>${http.client.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.core5</groupId>
                <artifactId>httpcore5</artifactId>
                <version>${http.core.version}</version>
            </dependency>
            <dependency>
                <groupId>io.opentracing.contrib</groupId>
                <artifactId>opentracing-spring-jaeger-web-starter</artifactId>
                <version>${jaeger.tracing.version}</version>
            </dependency>
            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>${freemarker.upgraded.version}</version>
            </dependency>

            <!-- Security -->
            <dependency>
                <groupId>org.pac4j</groupId>
                <artifactId>pac4j-saml</artifactId>
                <version>${pac4j.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>spring-beans</artifactId>
                        <groupId>org.springframework</groupId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-orm</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.pac4j</groupId>
                <artifactId>pac4j-oidc</artifactId>
                <version>${pac4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.pac4j</groupId>
                <artifactId>pac4j-jwt</artifactId>
                <version>${pac4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.pac4j</groupId>
                <artifactId>pac4j-core</artifactId>
                <version>${pac4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.security</groupId>
                <artifactId>spring-security-cas</artifactId>
                <version>${spring-security-cas.version}</version>
            </dependency>

            <!-- Apereo CAS Server Core Api Ticket -->
            <dependency>
                <groupId>org.apereo.cas</groupId>
                <artifactId>cas-server-core-api-ticket</artifactId>
                <version>${cas.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apereo.cas</groupId>
                <artifactId>cas-server-core-tickets-api</artifactId>
                <version>${cas.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>*</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- Web -->
            <dependency>
                <groupId>jakarta.servlet</groupId>
                <artifactId>jakarta.servlet-api</artifactId>
                <version>${jakarta.servlet.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.ws.rs</groupId>
                <artifactId>jakarta.ws.rs-api</artifactId>
                <version>${jakarta.ws.rs.version}</version>
            </dependency>

            <!-- Log -->
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>jcl-over-slf4j</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>jul-to-slf4j</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-ext</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>

            <!-- Metrics -->
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-registry-prometheus</artifactId>
                <version>${micrometer.version}</version>
            </dependency>

            <!-- VITAM -->
            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>ingest-external-client</artifactId>
                <version>${vitam.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.mongodb</groupId>
                        <artifactId>mongo-java-driver</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-to-slf4j</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>access-external-client</artifactId>
                <version>${vitam.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.mongodb</groupId>
                        <artifactId>mongo-java-driver</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-to-slf4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.mail</groupId>
                        <artifactId>mailapi</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-all</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>collect-external-client</artifactId>
                <version>${vitam.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.mongodb</groupId>
                        <artifactId>mongo-java-driver</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.apache.logging.log4j</groupId>
                        <artifactId>log4j-to-slf4j</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>javax.mail</groupId>
                        <artifactId>mailapi</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>io.netty</groupId>
                        <artifactId>netty-all</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>common-public</artifactId>
                <version>${vitam.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>common-database-public</artifactId>
                <version>${vitam.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>logbook-common</artifactId>
                <version>${vitam.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.gouv.vitam</groupId>
                <artifactId>common-dsl-schema</artifactId>
                <version>${vitam.version}</version>
            </dependency>
            <!-- swagger -->
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger2</artifactId>
                <version>${swagger.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.fasterxml.jackson.core</groupId>
                        <artifactId>jackson-annotations</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>io.springfox</groupId>
                <artifactId>springfox-swagger-ui</artifactId>
                <version>${swagger.version}</version>
            </dependency>

            <!-- APACHE ODFtoolKit-->
            <dependency>
                <groupId>org.odftoolkit</groupId>
                <artifactId>odfdom-java</artifactId>
                <version>${org.odftoolkit.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>tools</artifactId>
                        <groupId>com.sun</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.odftoolkit</groupId>
                <artifactId>simple-odf</artifactId>
                <version>${org.apache.odftoolkit.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>tools</artifactId>
                        <groupId>com.sun</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!-- APACHE ODFtoolKit-->

            <!-- Utils -->
            <dependency>
                <groupId>org.synchronoss.cloud</groupId>
                <artifactId>nio-multipart-parser</artifactId>
                <version>${nio.multipart.parser.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-collections4</artifactId>
                <version>${commons.collections4.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-fileupload</groupId>
                <artifactId>commons-fileupload</artifactId>
                <version>${commons.fileupload.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-beanutils</groupId>
                <artifactId>commons-beanutils</artifactId>
                <version>${commons.beanutils.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-compress</artifactId>
                <version>${commons.compress.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-text</artifactId>
                <version>${commons.text.version}</version>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>

            <!-- Dependency for Lombok-->
            <dependency>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.xebia.extras</groupId>
                <artifactId>selma-processor</artifactId>
                <version>${selma.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>fr.xebia.extras</groupId>
                <artifactId>selma</artifactId>
                <version>${selma.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.validation</groupId>
                <artifactId>jakarta.validation-api</artifactId>
                <version>${jakarta.validation.api.version}</version>
            </dependency>
            <dependency>
                <groupId>org.hibernate.validator</groupId>
                <artifactId>hibernate-validator</artifactId>
                <version>${hibernate.validatior.version}</version>
            </dependency>

            <dependency>
                <groupId>jakarta.el</groupId>
                <artifactId>jakarta.el-api</artifactId>
                <version>${jakarta.el.version}</version>
            </dependency>


            <dependency>
                <groupId>commons-codec</groupId>
                <artifactId>commons-codec</artifactId>
                <version>${apache.commons.codec.version}</version>
            </dependency>

            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-yaml</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.dataformat</groupId>
                <artifactId>jackson-dataformat-csv</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-databind</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
                <version>${jackson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-annotations</artifactId>
                <version>${jackson-annotation.version}</version>
            </dependency>

            <dependency>
                <groupId>commons-io</groupId>
                <artifactId>commons-io</artifactId>
                <version>${commons.io.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.springframework.shell</groupId>
                        <artifactId>spring-shell</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>xml-apis</groupId>
                <artifactId>xml-apis</artifactId>
                <version>${xml.apis-version}</version>
            </dependency>
            <dependency>
                <groupId>com.google.code.gson</groupId>
                <artifactId>gson</artifactId>
                <version>${gson.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.poi</groupId>
                <artifactId>poi-ooxml</artifactId>
                <version>${poi.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>${jakarta.xml.binding.version}</version>
            </dependency>
            <dependency>
                <groupId>org.glassfish.jaxb</groupId>
                <artifactId>jaxb-runtime</artifactId>
                <version>${glassfish.jaxb.version}</version>
            </dependency>

            <dependency>
                <groupId>xml-resolver</groupId>
                <artifactId>xml-resolver</artifactId>
                <version>${xml.resolver.version}</version>
            </dependency>
            <dependency>
                <groupId>xom</groupId>
                <artifactId>xom</artifactId>
                <version>${xom.version}</version>
            </dependency>
            <dependency>
                <groupId>org.bouncycastle</groupId>
                <artifactId>bcprov-jdk18on</artifactId>
                <version>${bouncycastle.version}</version>
            </dependency>
            <!-- convert xsd to xml -->
            <dependency>
                <groupId>in.jlibs</groupId>
                <artifactId>jlibs-xsd</artifactId>
                <version>${jlibs.version}</version>
            </dependency>
            <!-- convert to PDF -->
            <!-- Do not reuse Apache FOP since its usage is deprecated -->
            <dependency>
                <groupId>org.apache.xmlgraphics</groupId>
                <artifactId>fop</artifactId>
                <version>${fop.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>javax.media</groupId>
                        <artifactId>jai-core</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.sun.media</groupId>
                        <artifactId>jai-codec</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <!-- Security -->
            <dependency>
                <groupId>org.owasp.antisamy</groupId>
                <artifactId>antisamy</artifactId>
                <version>${antisamy.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>xercesImpl</artifactId>
                        <groupId>xerces</groupId>
                    </exclusion>
                </exclusions>
            </dependency>

            <dependency>
                <groupId>org.owasp.esapi</groupId>
                <artifactId>esapi</artifactId>
                <version>${esapi.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>log4j</artifactId>
                        <groupId>log4j</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>commons-fileupload</artifactId>
                        <groupId>commons-fileupload</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>commons-beanutils-core</artifactId>
                        <groupId>commons-beanutils</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>xalan</artifactId>
                        <groupId>xalan</groupId>
                    </exclusion>
                    <exclusion>
                        <artifactId>xercesImpl</artifactId>
                        <groupId>xerces</groupId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.owasp.antisamy</groupId>
                        <artifactId>antisamy</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.json</groupId>
                <artifactId>json</artifactId>
                <version>${json.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mikesamuel</groupId>
                <artifactId>json-sanitizer</artifactId>
                <version>${json-sanitize.version}</version>
            </dependency>
            <dependency>
                <groupId>com.sun.mail</groupId>
                <artifactId>jakarta.mail</artifactId>
                <version>${jakarta.mail.version}</version>
            </dependency>

            <!-- Test -->
            <dependency>
                <groupId>fr.gouv.vitamui.commons</groupId>
                <artifactId>commons-test</artifactId>
                <version>${project.version}</version>
                <type>test-jar</type>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.javassist</groupId>
                <artifactId>javassist</artifactId>
                <version>${javassist.version}</version>
            </dependency>
            <dependency>
                <groupId>org.skyscreamer</groupId>
                <artifactId>jsonassert</artifactId>
                <version>${jsonassert.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>${apache.pdfbox.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>mongodb</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${testcontainers.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- CUCUMBER SERENITY -->
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-core</artifactId>
                <version>${serenity.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-junit</artifactId>
                <version>${serenity.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-screenplay</artifactId>
                <version>${serenity.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-screenplay-webdriver</artifactId>
                <version>${serenity.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-spring</artifactId>
                <version>${serenity-spring.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>net.serenity-bdd</groupId>
                <artifactId>serenity-cucumber5</artifactId>
                <version>${serenity.cucumber.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>com.github.stefanbirkner</groupId>
                <artifactId>fake-sftp-server-rule</artifactId>
                <version>${fake.sftp.server.rule.version}</version>
                <scope>test</scope>
            </dependency>

            <!-- XDocReport convert ODT to PDF -->
            <dependency>
                <groupId>xerces</groupId>
                <artifactId>xercesImpl</artifactId>
                <version>${xerces.version}</version>
            </dependency>

            <dependency>
                <groupId>fr.opensagres.xdocreport</groupId>
                <artifactId>fr.opensagres.odfdom.converter.core</artifactId>
                <version>${xdocreport.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.opensagres.xdocreport</groupId>
                <artifactId>fr.opensagres.xdocreport.converter.odt.odfdom</artifactId>
                <version>${xdocreport.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.opensagres.xdocreport</groupId>
                <artifactId>fr.opensagres.xdocreport.document.odt</artifactId>
                <version>${xdocreport.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.opensagres.xdocreport</groupId>
                <artifactId>fr.opensagres.xdocreport.template.freemarker</artifactId>
                <version>${xdocreport.version}</version>
            </dependency>
            <dependency>
                <groupId>fr.opensagres.xdocreport</groupId>
                <artifactId>fr.opensagres.xdocreport.template.velocity</artifactId>
                <version>${xdocreport.version}</version>
            </dependency>

            <dependency>
                <groupId>com.opencsv</groupId>
                <artifactId>opencsv</artifactId>
                <version>${opencsv.version}</version>
            </dependency>
            <dependency>
                <groupId>uk.co.jemos.podam</groupId>
                <artifactId>podam</artifactId>
                <version>${podam.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>com.sun.istack</groupId>
                <artifactId>istack-commons-runtime</artifactId>
                <version>${istack-commons-runtime.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc-openapi-starter-webmvc-ui.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless-maven-plugin.version}</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <!-- Profile to use for all Vitam internal developers -->
            <id>vitam</id>
            <activation>
                <activeByDefault>false</activeByDefault>
            </activation>
            <!-- Dépôts Maven privés -->
            <distributionManagement>
                <repository>
                    <id>vitam-releases</id>
                    <name>Vitam release repository</name>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-releases/</url>
                </repository>
                <snapshotRepository>
                    <id>vitam-snapshots</id>
                    <name>Vitam SNAPSHOT repository</name>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-snapshots/</url>
                </snapshotRepository>
                <site>
                    <id>${project.artifactId}-site</id>
                    <url>${project.baseUri}</url>
                </site>
            </distributionManagement>

            <repositories>
                <repository>
                    <id>vitam-releases</id>
                    <name>Vitam release repository</name>
                    <releases>
                        <enabled>true</enabled>
                    </releases>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-releases/</url>
                </repository>
                <repository>
                    <id>vitam-snapshots</id>
                    <name>Vitam SNAPSHOT repository</name>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                    <url>${env.SERVICE_NEXUS_URL}/repository/maven-snapshots/</url>
                </repository>
            </repositories>

            <properties>
                <serverId>vitam</serverId>
                <downloadRoot>${env.SERVICE_NEXUS_URL}/repository/node-distrib/</downloadRoot>
            </properties>
        </profile>
    </profiles>
</project>
