# TECHNICAL PROPERTIES / DON'T put environment properties
# This property can be override by a config file give at run time with spring.config.location

spring:
    application:
        name: ingest-internal
    api:
        name: API Ingest
        description: This API is used to manage ingests
        version: v1
    jackson:
        serialization:
            write-dates-as-timestamps: false
    jmx:
        unique-names: true

management:
    endpoints:
        jmx:
            domain: ingest-internal
        web.exposure.include: info,health,prometheus
    endpoint:
        health:
            show-details: always
        prometheus:
            enabled: true

metrics:
    reporterInterval: 1
    reporterIntervalUnit: MINUTES
    index: metrics-vitam-jvm
