name: Publish design system
run-name: Publishing design system for branch ${{ github.ref }}
on: workflow_dispatch
jobs:
  build-and-publish-design-system:
    name: Build design system
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.20.3"
          cache: "npm"
          cache-dependency-path: |
            ui/ui-frontend/package-lock.json
      - name: Install ui-frontend dependencies
        working-directory: ui/ui-frontend
        run: npm ci
      - name: Build vitamui-library
        working-directory: ui/ui-frontend
        run: npm run build:vitamui-library
      - name: Build design-system app
        working-directory: ui/ui-frontend
        run: npm run build:design-system -- --base-href=/vitam-ui/${{ github.ref_name }}/ --deploy-url=/vitam-ui/${{ github.ref_name }}/
      - name: Publish design system to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ui/ui-frontend/dist/design-system/browser
          destination_dir: ${{ github.ref_name }}
          keep_files: true
          allow_empty_commit: false
      - name: Update index.html
        uses: ./.github/actions/update-gh-pages-index
